name: ls_business
description: "Vendor App For Localsearch"

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.0
  uuid: ^4.3.3
  image_picker: ^1.0.7
  provider: ^6.1.1
  carousel_slider: ^5.0.0
  path_provider: ^2.1.2
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  fl_chart: ^0.69.0
  feather_icons: ^1.2.0
  shimmer: ^3.0.0
  video_player: ^2.8.6
  video_compress: ^3.1.2
  flick_video_player: ^0.9.0
  geolocator: any
  http: any
  url_launcher: ^6.3.0
  open_street_map_search_and_pick: ^0.1.1
  modal_progress_hud_nsn: ^0.5.1
  youtube_player_flutter: ^9.1.0
  in_app_update: ^4.2.3
  package_info_plus: ^8.0.2
  flutter_image_compress: ^2.3.0
  # flutter_automation: any
  # lottie: ^3.0.0
  # shared_preferences: ^2.2.2
  # cached_network_image: ^3.3.1
  # geolocator: ^13.0.1
  # http: ^1.2.1
  # flutter_osm_plugin: ^1.3.0
  # image: ^4.2.0
  # firebase_ml_model_downloader: ^0.3.1+2
  # tflite_flutter: ^0.11.0
  # image: ^4.2.0
  # firebase_ml_model_downloader: ^0.3.1+2
  # tflite_flutter: ^0.11.0
  # flutter_email_sender: ^6.0.3
  # feedback: ^3.1.0
  # flutter_lints: ^4.0.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^4.0.0

flutter:
  uses-material-design: true