import 'package:flutter/material.dart';

final Map<String, List<List<dynamic>>> businessCategoryProperties = {
  // Name, Hint Text, No of Answers, DropDown Items, TextInputType, Max Lines, Mandatory Info
  'Grocery': [
    [
      'Weight (gm)',
      'in grams',
      1,
      [''],
      TextInputType.number,
      1,
      true,
    ],
    [
      'Shelf Life (months)',
      'in Months',
      1,
      [''],
      TextInputType.number,
      1,
      true,
    ],
    [
      'Form',
      'eg. Liquid, Flaked, Syrup...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Local/Imported',
      '',
      2,
      ['Local', 'Imported'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Diet Type',
      '',
      2,
      ['Vegetarian', 'Vegan'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Not Suitable For',
      'eg. Diabetis, Asthma',
      1,
      [''],
      TextInputType.text,
      10,
      false,
    ],
  ],
  'Pharmacies': [
    [
      'Medicine Type',
      'eg. Painkiller, Antibiotic...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Dosage',
      'eg. 500mg, 1g...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Form',
      '',
      2,
      ['Tablet', 'Capsule', 'Liquid', 'Injection'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Prescription Required',
      '',
      2,
      ['Yes', 'No'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Manufacturer',
      'eg. Pfizer, Johnson & Johnson...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Side Effects',
      'eg. Nausea, Headache...',
      1,
      [''],
      TextInputType.text,
      3,
      false,
    ],
  ],
  'Electronics': [
    [
      'Brand',
      'eg. Apple, Samsung, Sony...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Model Number',
      'Model or SKU',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Colors Available',
      'eg. Blue, Black',
      3,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Warranty Period',
      'in Months',
      1,
      [''],
      TextInputType.number,
      1,
      false,
    ],
    [
      'Connectivity Options',
      'eg. WiFi, Bluetooth...',
      3,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Special Features',
      'eg. Waterproof, Noise Cancelling...',
      3,
      [''],
      TextInputType.text,
      3,
      false,
    ],
  ],
  'Clothing and Apparel': [
    [
      'Brand',
      'eg. Nike, Adidas, Zara...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Sizes Available',
      'eg. XS, S, M, L, XL, XXL...',
      3,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Material',
      'eg. Cotton, Polyester...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Colors Available',
      'eg. Red, Blue, Green, Black, White...',
      3,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Fit Type',
      '',
      2,
      ['Slim', 'Regular', 'Loose'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Care Instructions',
      'eg. Machine wash, Hand wash...',
      1,
      [''],
      TextInputType.text,
      3,
      false,
    ],
  ],
  'Restaurant & Cafes': [
    [
      'Cuisine',
      '',
      2,
      ['Italian', 'Mexican', 'Chinese', 'Indian', 'Japanese', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Toppings',
      'eg. Cheese, Bacon, Mushrooms...',
      3,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Ingredients',
      'eg. Tomato, Lettuce, Onion...',
      3,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Beauty and Cosmetics': [
    [
      'Skin Type',
      '',
      2,
      ['Dry', 'Oily', 'Combination', 'Sensitive', 'Normal'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Ingredients',
      'eg. Retinol, Hyaluronic Acid...',
      3,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Furniture': [
    [
      'Type',
      '',
      2,
      ['Sofa', 'Bed', 'Table', 'Chair', 'Cabinet', 'Other'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Material',
      'eg. Wood, Metal, Glass...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Dimensions',
      'eg. 120cm x 80cm x 40cm...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Assembly Required',
      '',
      2,
      ['Yes', 'No'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Color',
      '',
      3,
      ['Black', 'White', 'Brown', 'Gray', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Additional Features',
      'eg. Storage, Foldable...',
      3,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Jewelry': [
    [
      'Material',
      'eg. Gold, Silver, Diamond...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Gemstone',
      '',
      2,
      ['Diamond', 'Ruby', 'Sapphire', 'Emerald', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Size',
      'eg. Small, Medium, Large...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Occasion',
      '',
      2,
      ['Casual', 'Formal', 'Wedding', 'Party', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Description',
      'eg. Engraved, Filigree...',
      1,
      [''],
      TextInputType.text,
      3,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Decorations': [
    [
      'Material',
      'eg. Ceramic, Metal, Glass...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Color',
      'eg. Black, Yellow',
      3,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Size',
      'eg. Small, Medium, Large...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Style',
      '',
      2,
      ['Modern', 'Vintage', 'Rustic', 'Minimalist', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Description',
      'eg. Hand-painted, Intricate design...',
      1,
      [''],
      TextInputType.text,
      3,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Bookstores and Stationery': [
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Category (For Books)',
      '',
      2,
      ['Fiction', 'Non-fiction', 'Sci-fi', 'Fantasy', 'Business', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Color (For Stationery)',
      '',
      3,
      ['Black', 'Blue', 'Red', 'Green', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Age Group',
      '',
      2,
      ['Children', 'Teenagers', 'Adults', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Genre (For Books)',
      '',
      2,
      ['Fiction', 'Non-fiction', 'Sci-fi', 'Fantasy', 'Business', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Building Materials and Hardware': [
    [
      'Material Type',
      '',
      2,
      ['Lumber', 'Concrete', 'Metal', 'Plastic', 'Other'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Quantity',
      'eg. 10 pieces, 5 liters...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Usage',
      '',
      2,
      ['Construction', 'Renovation', 'DIY Projects', 'Repair', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Size',
      'eg. 2x4x8, 10kg, Small...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Color',
      'eg. White, Grey',
      3,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Description',
      'eg. High strength, Waterproof...',
      1,
      [''],
      TextInputType.text,
      3,
      false,
    ],
  ],
  'Automobile Parts and Accessories': [
    [
      'Part Type',
      '',
      2,
      ['Engine', 'Brakes', 'Transmission', 'Suspension', 'Lighting', 'Other'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Vehicle Compatibility',
      'eg. For Bikes / Cars',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Quantity',
      'eg. 1 piece, Set of 4...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Color',
      'eg. Black, Grey',
      3,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Material',
      'eg. Steel, Aluminum, Plastic...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Condition',
      '',
      2,
      ['New', 'Used'],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Gifts and Novelty': [
    [
      'Type',
      '',
      2,
      ['Mug', 'Keychain', 'Photo Frame', 'Plush Toy', 'Greeting Card', 'Other'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Quantity',
      'eg. 1 piece, Set of 4...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Occasion',
      '',
      2,
      ['Birthday', 'Anniversary', 'Christmas', 'Valentine\'s Day', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Recipient',
      '',
      2,
      ['Friend', 'Family', 'Colleague', 'Partner', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Color',
      'eg. Red, Pink',
      3,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Material',
      'eg. Ceramic, Metal, Fabric...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Toys': [
    [
      'Quantity',
      'eg. 1 piece, Set of 4...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Battery Powered',
      '',
      2,
      ['Yes', 'No'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Age Group',
      '',
      2,
      ['Infants', 'Toddlers', 'Preschoolers', 'School Age', 'Teens', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Gender',
      '',
      2,
      ['Boys', 'Girls', 'Unisex'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Material',
      'eg. Plastic, Wood, Fabric...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Color',
      '',
      3,
      ['Red', 'Blue', 'Green', 'Yellow', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Sports Goods': [
    [
      'Sport Type',
      '',
      2,
      ['Football', 'Basketball', 'Tennis', 'Golf', 'Swimming', 'Other'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Quantity',
      'eg. 1 piece, Set of 2...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Age Group',
      '',
      2,
      ['Kids', 'Teens', 'Adults'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Material',
      'eg. Leather, Plastic, Metal...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Color',
      'eg. Black, Red',
      3,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Size',
      'eg. Small, Medium, Large...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Agriculture and Farm Supply': [
    [
      'Quantity',
      'eg. 1 bag, Set of 10...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Crop Type',
      '',
      2,
      ['Grains', 'Vegetables', 'Fruits', 'Herbs', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Usage',
      '',
      2,
      ['Planting', 'Fertilizing', 'Pest Control', 'Harvesting', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Size',
      'eg. 1kg, 5 liters, Small...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      3,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Other': [
    [
      'Category',
      '',
      2,
      [
        'Electronics',
        'Clothing',
        'Toys',
        'Sports Goods',
        'Books',
        'Furniture',
        'Gifts',
        'Automobile Parts',
        'Agriculture',
        'Other'
      ],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Color',
      '',
      3,
      ['Red', 'Blue', 'Green', 'Yellow', 'Black', 'White', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Material',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Size',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Quantity',
      '',
      1,
      [''],
      TextInputType.number,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
};
