Map<String, Map<String, List<String>>> householdTypeCategorySubCategory = {
  'Fashion & Clothing': {
    'Active Wear': [
      'Track Pants',
      'Running Tights',
      'Yoga Pants',
      'Athletic Shorts',
      'Sports Bras',
      'Gym T-Shirts',
      'Compression Leggings',
      'Training Jackets',
      'Other Active Wear',
    ],
    'Hoodies': [
      'Pullover Hoodies',
      'Zipper Hoodies',
      'Graphic Hoodies',
      'Oversized Hoodies',
      'Cotton Hoodies',
      'Sports Hoodies',
      'Woollen Hoodies',
      'Fleece Hoodies',
      'Other Hoodies',
    ],
    'Kids Ethnic Wear': [
      'Kurta Pajama Sets',
      'Sherwani for Kids',
      'Lehenga Choli',
      'Dhoti Kurta',
      'Jacket Style Kurtas',
      'Pathani Suits',
      'Anarkali Dresses',
      'Angrakha Kurtas',
      'Other Kids Ethnic Wear',
    ],
    'Kids Innerwear': [
      'Cotton Vests',
      'Boxer Shorts',
      'Briefs',
      'Thermal Sets',
      'Undershirts',
      'Camisoles',
      'Training Bras',
      'Night Slips',
      'Other Kids Innerwear',
    ],
    'Kids Jeans': [
      'Denim Jeans',
      'Slim Fit Jeans',
      'Distressed Jeans',
      'Cargo Jeans',
      'Printed Jeans',
      'Jogger Jeans',
      'Stretchable Jeans',
      'Straight Fit Jeans',
      'Other Kids Jeans',
    ],
    'Kids Joggers': [
      'Cotton Joggers',
      'Athletic Joggers',
      'Printed Joggers',
      'Denim Joggers',
      'Cuffed Joggers',
      'Relaxed Fit Joggers',
      'Zipper Joggers',
      'Track Joggers',
      'Other Kids Joggers',
    ],
    'Kids Shirts': [
      'Casual Shirts',
      'Formal Shirts',
      'Printed Shirts',
      'Plaid Shirts',
      'Linen Shirts',
      'Denim Shirts',
      'Mandarin Collar Shirts',
      'Party Wear Shirts',
      'Other Kids Shirts',
    ],
    'Kids Shorts': [
      'Denim Shorts',
      'Cotton Shorts',
      'Cargo Shorts',
      'Athletic Shorts',
      'Printed Shorts',
      'Knee-Length Shorts',
      'Relaxed Fit Shorts',
      'Sweat Shorts',
      'Other Kids Shorts',
    ],
    'Kids T Shirts': [
      'Graphic T-Shirts',
      'Plain T-Shirts',
      'Polo T-Shirts',
      'Striped T-Shirts',
      'Round Neck T-Shirts',
      'Henley T-Shirts',
      'Cartoon Printed T-Shirts',
      'Sleeveless T-Shirts',
      'Other Kids T-Shirts',
    ],
    'Kids Western Wear': [
      'Party Dresses',
      'Jumpsuits',
      'Tops and Skirts',
      'Gowns',
      'Shrugs',
      'Shorts and Tops Sets',
      'Dungarees',
      'Playsuits',
      'Other Kids Western Wear',
    ],
    'Kids Winter Wear': [
      'Sweaters',
      'Jackets',
      'Thermal Wear',
      'Hoodies',
      'Fleece Jackets',
      'Cardigans',
      'Woollen Caps',
      'Gloves and Mufflers',
      'Other Kids Winter Wear',
    ],
    'Men Accessories': [
      'Belts',
      'Ties',
      'Cufflinks',
      'Caps',
      'Wallets',
      'Sunglasses',
      'Wristbands',
      'Keychains',
      'Other Men Accessories',
    ],
    'Men Ethnic Wear': [
      'Kurta Pajama',
      'Sherwani',
      'Pathani Suits',
      'Nehru Jackets',
      'Dhoti Suits',
      'Indo-Western Suits',
      'Angrakha Kurtas',
      'Jodhpuri Suits',
      'Other Men Ethnic Wear',
    ],
    'Men Innerwear': [
      'Boxers',
      'Briefs',
      'Vests',
      'Thermal Wear',
      'Undershirts',
      'Lounge Pants',
      'Compression Shorts',
      'Cotton Trunks',
      'Other Men Innerwear',
    ],
    'Men Jeans': [
      'Slim Fit Jeans',
      'Straight Fit Jeans',
      'Ripped Jeans',
      'Bootcut Jeans',
      'Skinny Jeans',
      'Washed Denim Jeans',
      'Stretchable Jeans',
      'Cargo Jeans',
      'Other Men Jeans',
    ],
    'Men Joggers': [
      'Athletic Joggers',
      'Casual Joggers',
      'Denim Joggers',
      'Cuffed Joggers',
      'Relaxed Fit Joggers',
      'Tapered Joggers',
      'Slim Fit Joggers',
      'Printed Joggers',
      'Other Men Joggers',
    ],
    'Men Shirts': [
      'Formal Shirts',
      'Casual Shirts',
      'Checked Shirts',
      'Linen Shirts',
      'Solid Shirts',
      'Floral Print Shirts',
      'Denim Shirts',
      'Mandarin Collar Shirts',
      'Other Men Shirts',
    ],
    'Men Shorts': [
      'Cargo Shorts',
      'Denim Shorts',
      'Chino Shorts',
      'Cotton Shorts',
      'Printed Shorts',
      'Relaxed Fit Shorts',
      'Athletic Shorts',
      'Sweat Shorts',
      'Other Men Shorts',
    ],
    'Men T Shirts': [
      'Graphic T-Shirts',
      'Polo T-Shirts',
      'Henley T-Shirts',
      'Striped T-Shirts',
      'Solid T-Shirts',
      'Round Neck T-Shirts',
      'V-Neck T-Shirts',
      'Sleeveless T-Shirts',
      'Other Men T-Shirts',
    ],
    'Men Western Wear': [
      'Blazers',
      'Suits',
      'Casual Jackets',
      'Party Wear Coats',
      'Trench Coats',
      'Leather Jackets',
      'Waistcoats',
      'Bomber Jackets',
      'Other Men Western Wear',
    ],
    'Men Winter Wear': [
      'Sweaters',
      'Hoodies',
      'Thermal Wear',
      'Overcoats',
      'Puffer Jackets',
      'Woollen Scarves',
      'Mufflers',
      'Gloves',
      'Other Men Winter Wear',
    ],
    'Night Wear': [
      'Pyjama Sets',
      'Nightgowns',
      'Robes',
      'Loungewear',
      'Sleep Shirts',
      'Nighties',
      'Two-Piece Sleepwear',
      'Cotton Nightwear',
      'Other Night Wear',
    ],
    'Punjabi Suits': [
      'Patiala Suits',
      'Straight Cut Suits',
      'Anarkali Suits',
      'Plazzo Suits',
      'Jacket Style Suits',
      'Phulkari Suits',
      'Designer Punjabi Suits',
      'Cotton Punjabi Suits',
      'Other Punjabi Suits',
    ],
    'Rainy Wear': [
      'Raincoats',
      'Waterproof Jackets',
      'Umbrellas',
      'Rain Boots',
      'Ponchos',
      'Rain Pants',
      'Rain Suits',
      'Plastic Sandals',
      'Other Rainy Wear',
    ],
    'Sarees': [
      'Silk Sarees',
      'Cotton Sarees',
      'Chiffon Sarees',
      'Designer Sarees',
      'Georgette Sarees',
      'Banarasi Sarees',
      'Kanjeevaram Sarees',
      'Printed Sarees',
      'Other Sarees',
    ],
    'Sunglasses': [
      'Aviator Sunglasses',
      'Wayfarer Sunglasses',
      'Round Sunglasses',
      'Sports Sunglasses',
      'Oversized Sunglasses',
      'Polarized Sunglasses',
      'Cat Eye Sunglasses',
      'Retro Sunglasses',
      'Other Sunglasses',
    ],
    'Wallets': [
      'Leather Wallets',
      'Bi-Fold Wallets',
      'Tri-Fold Wallets',
      'Card Holders',
      'Travel Wallets',
      'Coin Pouches',
      'RFID Blocking Wallets',
      'Slim Wallets',
      'Other Wallets',
    ],
    'Watches': [
      'Analog Watches',
      'Digital Watches',
      'Smartwatches',
      'Chronograph Watches',
      'Luxury Watches',
      'Sports Watches',
      'Casual Watches',
      'Vintage Watches',
      'Other Watches',
    ],
    'Women Accessories': [
      'Scarves',
      'Jewelry',
      'Handbags',
      'Hair Clips',
      'Earrings',
      'Bracelets',
      'Brooches',
      'Anklets',
      'Other Women Accessories',
    ],
    'Women Ethnic Wear': [
      'Anarkali Suits',
      'Lehengas',
      'Salwar Suits',
      'Kurtis',
      'Sarees',
      'Sharara Suits',
      'Gharara Sets',
      'Palazzo Suits',
      'Other Women Ethnic Wear',
    ],
    'Women Innerwear': [
      'Bras',
      'Panties',
      'Shapewear',
      'Camisoles',
      'Lingerie Sets',
      'Sports Bras',
      'Thermal Innerwear',
      'Lace Panties',
      'Other Women Innerwear',
    ],
    'Women Jeans': [
      'Skinny Jeans',
      'Straight Fit Jeans',
      'High-Waist Jeans',
      'Bootcut Jeans',
      'Boyfriend Jeans',
      'Flared Jeans',
      'Distressed Jeans',
      'Stretchable Jeans',
      'Other Women Jeans',
    ],
  },
  'Food': {
    'Daily Needs': [
      'Fruits',
      'Vegetables',
      'Milk & Other Dairy Products',
      'Grains',
      'Cereals',
      'Rice',
      'Beverages',
      'Condiments',
      'Ice Creams & Other Frozen Foods',
      'Juices & Shakes',
      'Spices',
      'Herbs',
      'Oils',
      'Nuts',
      'Seeds',
      'Other Daily Needs',
    ],
    'Ready To Eat Food': [
      'Baked Food',
      'Canned Food',
      'Packet Food',
      'Frozen Food',
      'Festive Special Food',
      'Indian Snacks',
      'Dry Snacks',
      'Roti & Sabji',
      'Thali',
      'Dal & Rice',
      'Gujarati Food',
      'Punjabi Food',
      'Rajasthani Food',
      'South Indian',
      'North Indian',
      'Sweets',
      'Cakes & Bakery Items',
      'Western',
      'Chinese',
      'Other Ready To Eat',
    ],
    'Bakery Items': [
      'Bread',
      'Muffins',
      'Pizza Base',
      'Cookies',
      'Biscuits',
      'Cakes',
      'Pastries',
      'Donuts',
      'Brownies',
      'Cupcakes',
      'Buns',
      'Other Bakery Items',
    ],
    'Namkeen': [
      'Sev',
      'Mixture',
      'Chivda',
      'Murukku/Chakli',
      'Mathri',
      'Nimki/Namak Para',
      'Dal-based Snacks',
      'Peanuts',
      'Gathiya',
      'Boondi',
      'Other Namkeen',
      'Khakra',
      'Farsan',
      'Khatta Meetha Mix',
      'Other Namkeen',
    ],
    'Snacks': [
      'Samosa',
      'Pakora (Bhajiya)',
      'Aloo Tikki',
      'Paneer Tikka',
      'Veg Cutlet',
      'Masala Vada',
      'Sabudana Vada',
      'Dhokla',
      'Khandvi',
      'Idli',
      'Medu Vada',
      'Vada Pav',
      'Batata Vada',
      'Methi na Gota',
      'Bread Pakora',
      'Hara Bhara Kabab',
      'Corn Fritters',
      'Chana Jor Garam',
      'Veg Spring Roll',
      'Pav Bhaji',
      'Bhel Puri',
      'Sev Puri',
      'Dabeli',
      'Pani Puri',
      'Ragda Pattice',
      'Moong Dal Chilla',
      'Chole Bhature',
      'Aloo Chaat',
      'Papdi Chaat',
      'Samosa Chaat',
      'Other Snacks',
    ],
    'Baked & Roasted Snacks': [
      'Roasted Chana',
      'Roasted Makhanas (Fox Nuts)',
      'Khakra',
      'Baked Mathri',
      'Baked Chakli',
      'Masala Peanuts (baked or roasted)',
      'Roasted Poha Chivda',
      'Bhel Mix (without sev)',
      'Baked Methi Crackers',
      'Baked Namak Pare',
      'Masala Papad (roasted)',
      'Baked Thepla Crackers',
      'Murmura (Puffed Rice)',
      'Chana Jor Garam (roasted)',
      'Baked Oats Chivda',
      'Roasted Bajra Puffs',
      'Roasted Moong Dal',
      'Baked Spiced Nuts',
      'Roasted Flax Seeds',
      'Roasted Pumpkin Seeds',
      'Baked Multigrain Chips',
      'Roasted Almonds with Spices',
      'Baked Ragi Chips',
      'Baked Beetroot Chips',
      'Roasted Cashews with Curry Leaves',
      'Spiced Murmura (Puffed Rice)',
      'Roasted Soy Nuts',
      'Baked Kale Chips (Indian Spices)',
      'Baked Vegetable Sticks',
      'Baked Lentil Cracker',
      'Other Baked & Roasted Snacks',
    ],
    'Chaat': [
      'Pani Puri (Golgappa)',
      'Bhel Puri',
      'Sev Puri',
      'Aloo Chaat',
      'Dahi Puri',
      'Pav Bhaji',
      'Ragda Pattice',
      'Papdi Chaat',
      'Samosa Chaat',
      'Dahi Bhalla',
      'Kachori Chaat',
      'Chole Bhature',
      'Aloo Tikki Chaat',
      'Pav Vada',
      'Masala Puri',
      'Dabeli',
      'Chana Chaat',
      'Moong Dal Chilla',
      'Raj Kachori',
      'Matar Kulcha',
      'Kutchi Dabeli',
      'Corn Chaat',
      'Fruit Chaat',
      'Churmuri',
      'Kanji Vada',
      'Tokri Chaat (Basket Chaat)',
      'Batata Vada',
      'Vada Pav',
      'Samosa Pav',
      'Khasta Kachori',
      'Misal Pav',
      'Dahi Papdi Chaat',
      'Bikaneri Bhujia',
      'Sabudana Vada',
      'Bread Pakora Chaat',
      'Methi na Gota (Methi Pakora) Chaat',
      'Roti Chaat',
      'Paneer Tikka Chaat',
      'Other Chaat',
    ],
    'Starters': [
      'Salads',
      'Papad',
      'Soups',
      'Raitas',
      'Other Starters',
    ],
    'Main Course': [
      'Roti',
      'Paratha',
      'Dal',
      'Rice',
      'Pulav',
      'Biryani',
      'Gravy Sabji',
      'Non Gravy Sabji',
      'Thali',
      'Other Main Course Items',
    ],
    'Gujarati Food': [
      'Gujarati Breakfast',
      'Gujarati Snacks & Farsan',
      'Gujarati Main Course',
      'Gujarati Thali',
      'Gujarati Specials',
      'Gujarati Sweets & Desserts',
      'Gujarati Rice Dishes',
      'Gujarati Chutneys & Pickles',
      'Other Gujarati Food',
    ],
    'Punjabi Food': [
      'Punjabi Breakfast',
      'Punjabi Snacks & Farsan',
      'Punjabi Main Course',
      'Punjabi Thali',
      'Punjabi Specials',
      'Punjabi Sweets & Desserts',
      'Punjabi Rice Dishes',
      'Punjabi Chutneys & Pickles',
      'Other Punjab Food',
    ],
    'Maharashtrian Food': [
      'Maharashtrian Breakfast',
      'Maharashtrian Snacks & Farsan',
      'Maharashtrian Main Course',
      'Maharashtrian Thali',
      'Maharashtrian Specials',
      'Maharashtrian Sweets & Desserts',
      'Maharashtrian Rice Dishes',
      'Maharashtrian Chutneys & Pickles',
      'Other Maharashtrian Food',
    ],
    'South Indian Food': [
      'South Indian Breakfast',
      'South Indian Snacks & Farsan',
      'South Indian Main Course',
      'South Indian Thali',
      'South Indian Specials',
      'South Indian Sweets & Desserts',
      'South Indian Rice Dishes',
      'South Indian Chutneys & Pickles',
      'Other South Indian Food',
    ],
    'Chinese Food': [
      'Chinese Appetizers',
      'Chinese Soups',
      'Chinese Main Course',
      'Chinese Gravy Dishes',
      'Chinese Sides & Sauces',
      'Other Chinese Food',
    ],
    'Western Food': [
      'Western Starters',
      'Western Appetizers',
      'Western Soups',
      'Western Desserts',
      'Pastas',
      'Pizzas',
      'Tacos',
      'Burgers',
      'Sandwiches',
      'French Fries',
      'Wraps',
      'Sides',
      'Lasagna',
      'Western Sides & Sauces',
      'Other Western Food',
    ],
    'Sweets & Desserts': [
      'Gulab Jamun',
      'Rasgulla',
      'Kaju Katli',
      'Jalebi',
      'Rasmalai',
      'Barfi',
      'Payasam',
      'Laddu',
      'Sooji Halwa',
      'Gajar ka Halwa',
      'Sandesh',
      'Peda',
      'Kheer',
      'Mysore Pak',
      'Mohanthal',
      'Khoya Burfi',
      'Basundi',
      'Shrikhand',
      'Malpua',
      'Chum Chum',
      'Petha',
      'Mishti Doi',
      'Rabri',
      'Chiroti',
      'Coconut Ladoo',
      'Malai Kofta',
      'Kalaadi',
      'Doodh Peda',
      'Khatta Meetha',
      'Anjeer Barfi',
      'Methi Thepla',
      'Suji Ka Halwa',
      'Gulkand',
      'Saffron Peda',
      'Thandai',
      'Bhapa Doi',
      'Rawa Kesari',
      'Doodhi Halwa',
      'Moong Dal Halwa',
      'Aloo Halwa',
      'Other Sweets & Desserts',
    ],
    'Beverages': [
      'Masala Chai',
      'Lassi',
      'Mango Lassi',
      'Buttermilk (Chaas)',
      'Coconut Water',
      'Jaljeera',
      'Aam Panna',
      'Falooda',
      'Thandai',
      'Nimbu Pani (Lemonade)',
      'Sugarcane Juice',
      'Badam Milk',
      'Rose Milk',
      'Sharbat',
      'Filter Coffee',
      'Sattu Drink',
      'Banana Smoothie',
      'Kokum Sherbet',
      'Solkadhi',
      'Apple Ginger Juice',
      'Pomegranate Juice',
      'Carrot and Beetroot Juice',
      'Kesar Milk',
      'Tulsi Tea',
      'Green Tea',
      'Almond Milkshake',
      'Dates Milkshake',
      'Ginger Lemon Tea',
      'Herbal Tea',
      'Mint Lemonade',
      'Turmeric Milk (Golden Milk)',
      'Watermelon Juice',
      'Pineapple Juice',
      'Amla Juice',
      'Cucumber Cooler',
      'Masala Soda',
      'Fennel Seed Drink (Saunf Sharbat)',
      'Hibiscus Tea',
      'Jaggery Water (Gur Sharbat)',
      'Bael Sharbat',
      'Other Beverages',
    ],
  },
  'Beauty & Care': {
    'Face': [
      'Primer',
      'Foundation',
      'Concealer',
      'Setting Powder',
      'Contour Stick/Powder',
      'Blush',
      'Bronzer',
      'Highlighter',
      'Setting Spray',
      'BB Cream',
      'CC Cream',
      'Tinted Moisturizer',
      'Other Face Beauty & Face Items',
    ],
    'Eyes': [
      'Eyeshadow Primer',
      'Eyeshadow Palettes',
      'Eyeliner',
      'Mascara',
      'Eyebrow Pencil',
      'Eyebrow Gel',
      'Eyebrow Powder',
      'False Eyelashes',
      'Other Eye Beauty & Care Items',
    ],
    'Lips': [
      'Lip Balm',
      'Lip Liner',
      'Matte Lipstick',
      'Glossy Lipstick',
      'Lipstick',
      'Lip Gloss',
      'Other Lip Beauty & Care Items',
    ],
    'Beard': [
      'Beard Filler',
      'Beard Balm/Oil',
      'Other Beard Beauty & Care Items',
    ],
    'Tools & Accessories': [
      'Combs',
      'Hair Ties',
      'Hair Clips',
      'Hair Bands',
      'Headbands',
      'Shower Cap',
      'Hair Scarves',
      'Makeup Remover',
      'Beauty Sponges',
      'Makeup Brush',
      'Styling Brush',
      'Eyelash Curler',
      'Tweezer',
      'Cotton Pads',
      'Brush Cleaner',
      'Blotting Paper',
      'Hair Dryer',
      'Curlings',
      'Towels',
      'Flat Iron',
      'Hair Rollers',
      'Hair Steamer',
      'Other Tools',
    ],
    'Hair Care & Styling': [
      'Shampoo',
      'Conditioners',
      'Hair Oils',
      'Hair Serums',
      'Hair Masks',
      'Hair Wax',
      'Hair Creams',
      'Hair Vitamins & Supplements',
      'Styling Gel',
      'Styling Lotion',
      'Hair Tonics',
      'Scalp Treatment',
      'Protein Treatment',
      'Hair Growth Serum',
      'Mousses',
      'Hair Spray',
      'Shine Spray',
      'Hair Pomade',
      'Styling Foam',
      'Other Hair Care & Styling Products',
    ],
    'Skin Care': [
      'Cleaner',
      'Toner',
      'Serum',
      'Moisturizer',
      'Creams',
      'Sunscreen',
      'Night Cream',
      'Anti-aging Cream',
      'Face Mask',
      'Sleeping Mask',
      'Aftershave Balm',
      'Beard Oil',
      'Facial Oil',
      'Pre-Shave Oil',
      'Face Scrub',
      'Hydrating Mist',
      'Exfoliator',
      'Pore Strips',
      'Other Skin Care Products'
    ],
  },
  'Cleaning Essentials': {
    'Cleaners': [
      'All Purpose Cleaner',
      'Glass Cleaner',
      'Bathroom Cleaner',
      'Kitchen Cleaner',
      'Floor Cleaner',
      'Carpet Cleaner',
      'Upholstery Cleaner',
      'Stainless Steel Cleaner',
      'Tile & Grout Cleaner',
      'Toilet Bowl Cleaner',
      'Oven Cleaner',
      'Drain Cleaner',
      'Hardwood Floor Cleaner',
      'Mold & Mildew Remover',
      'Stain Remover',
      'Disinfectant Spray',
      'Furniture Polish',
      'Dish Soap',
      'Laundry Detergent',
      'Fabric Softener',
      'Other Cleaners',
    ],
    'Cleaning Tools': [
      'Broom',
      'Dustpan',
      'Mop',
      'Bucket',
      'Vacuum Cleaner',
      'Duster',
      'Microfiber Cloths',
      'Scrub Brush',
      'Sponge',
      'Squeengee',
      'Cleaning Gloves',
      'Lint Roller',
      'Toilet Brush',
      'Spray Bottle',
      'Cleaning Caddy',
      'Steam Cleaner',
      'Rubber Gloves',
      'Dust Mop',
      'Scouring Pad',
      'Cleaning Wipes',
      'Other Tools',
    ],
  },
  'Health Care': {
    'Ayurvedic Products': [
      'Chyawanprash',
      'Herbal Supplements',
      'Herbal Teas',
      'Herbal Powders',
      'Ayurvedic Oils',
      'Tablets and Capsules',
      'Juices',
      'Face Packs',
      'Detox Products',
      'Nasal Drops',
      'Tonics',
      'Syrups',
      'Balms',
      'Herbal Ghee',
      'Digestive Aids',
      'Herbal Extracts',
      'Creams and Lotions',
      'Oral Health Products',
      'Hair Care Products',
      'Body Scrubs',
      'Bath Powders',
      'Massage Oils',
      'Immunity Boosters',
      'Sleep Aids',
      'Energy Supplements',
      'Menstrual Health Products',
      'Joint Care Supplements',
      'Weight Management Products',
      'Skin Care Oil',
      'Other Ayurvedic Products',
    ],
    'Homeopathy': [
      'Mother Tinctures',
      'Tablets',
      'Pellets',
      'Syrups',
      'Ointments',
      'Drops',
      'Powders',
      'Nasal Drops',
      'Oral Solutions',
      'Creams',
      'Gels',
      'Pastes',
      'Immune Products',
      'Herbal Products',
      'Cough Syrups',
      'Allergy Products',
      'Digestive Aids',
      'Skin Care Products',
      'Pain Relief Products',
      'Sleep Aids',
      'Hormonal Balance Products',
      'Eye Care Products',
      'Ear Care Products',
      'Dental Care Products',
      'Women\'s Products',
      'Other Homeopathy Products',
    ],
    'Personal Care': [
      'Cleansers',
      'Moisturizers',
      'Shampoos',
      'Conditioners',
      'Body Washes',
      'Scrubs',
      'Face Masks',
      'Lip Balms',
      'Sunscreens',
      'Hair Oils',
      'Deodorants',
      'Hand Creams',
      'Foot Creams',
      'Toothpastes',
      'Body Lotions',
      'Facial Serums',
      'Toners',
      'Exfoliators',
      'Hair Masks',
      'Body Butters',
      'Bath Salts',
      'Anti-aging Creams',
      'Eye Creams',
      'Shaving Creams',
      'Beard Oils',
      'Body Sprays',
      'Nail Care Products',
      'Hair Styling Products',
      'Makeup Removers',
      'Hand Sanitizers',
      'Other Personal Care Products',
    ],
    'Sports Suplemments': [
      'Protein Powders',
      'Amino Acids',
      'BCAA (Branched-Chain Amino Acids)',
      'Pre-Workout Supplements',
      'Post-Workout Recovery',
      'Creatine',
      'Multivitamins',
      'Electrolyte Powders',
      'Energy Bars',
      'Sports Drinks',
      'Omega-3 Supplements',
      'Glutamine',
      'Casein Protein',
      'Plant-Based Protein Blends',
      'Joint Support Supplements',
      'Performance Enhancers',
      'Adaptogens',
      'Fat Burners',
      'Herbal Recovery Aids',
      'Hydration Tablets',
      'Recovery Drinks',
      'Vegan BCAA',
      'Vegan Creatine',
      'Superfood Powders',
      'Collagen Supplements',
      'Immune Support Supplements',
      'Antioxidant Supplements',
      'Natural Test Boosters',
      'Caffeine Supplements',
      'Electrolyte Tablets',
      'Other Sports Supplements',
    ],
    'Diet & Nutrition': [
      'Protein Powders',
      'Meal Replacement Shakes',
      'Nutritional Bars',
      'Multivitamins',
      'Omega-3 Supplements',
      'Fiber Supplements',
      'Probiotics',
      'Superfood Powders',
      'Green Tea Extracts',
      'Herbal Supplements',
      'Energy Drinks',
      'Amino Acids',
      'Vitamin D Supplements',
      'Iron Supplements',
      'Calcium Supplements',
      'Collagen Supplements',
      'Antioxidant Supplements',
      'Herbal Teas',
      'Adaptogens',
      'Detox Powders',
      'Sports Supplements',
      'Weight Management Supplements',
      'Electrolyte Supplements',
      'Digestive Enzymes',
      'Vegan Omega-3',
      'Plant-Based Meal Additives',
      'Supergreens Powders',
      'Energy Tablets',
      'Vitamin B12 Supplements',
      'Antioxidant Capsules',
      'Other Diet & Nutrition Products',
    ],
    'Health Care Devices': [
      'Blood Pressure Monitors',
      'Glucometers',
      'Digital Thermometers',
      'Pulse Oximeters',
      'Weighing Scales',
      'Nebulizers',
      'Fitness Trackers',
      'ECG Monitors',
      'Blood Glucose Meters',
      'Hearing Aids',
      'Sleep Apnea Devices',
      'Blood Oxygen Monitors',
      'Infrared Thermometers',
      'Personal ECG Devices',
      'Home Care Nebulizers',
      'Body Fat Scales',
      'Smartwatches with Health Tracking',
      'Respiratory Inhalers',
      'Digital Stethoscopes',
      'Temperature Sensors',
      'Home ECG Monitors',
      'Activity Monitors',
      'Body Composition Analyzers',
      'Pulse Massagers',
      'Infrared Heat Therapy Devices',
      'Personal Blood Pressure Monitors',
      'Automated External Defibrillators (AEDs)',
      'Smart Glucose Monitors',
      'Oxygen Concentrators',
      'Wearable Health Monitor',
      'Other Health Care Devices',
    ],
  },
  'Jewelry': {
    'Neck': [
      'Necklace',
      'Pearl Necklace',
      'Choker',
      'Pendant Set',
      'Mangalsutra',
      'Tika',
      'Chain',
      'Collar',
      'Rani Haar',
      'Satlada',
      'Locket',
      'Choker Set',
      'Traditional Necklace',
      'Modern Necklace',
      'Multi-layered Necklace',
      'Other Neck Jewelry',
    ],
    'Legs': [
      'Payal',
      'Bichiya',
      'Ghungroo',
      'Toe Rings',
      'Toe Anklets',
      'Other Legs Jewelry',
    ],
    'Hands': [
      'Bangles',
      'Bracelets',
      'Kadas',
      'Chuda',
      'Rakhdi',
      'Kangan',
      'Armlets',
      'Hathphool',
      'Kada Bangles',
      'Traditional Bangles',
      'Other Hands Jewelry',
    ],
    'Face': [
      'Naths',
      'Nose Pins',
      'Nose Rings',
      'Maang Tikka',
      'Bindi',
      'Earring Tops',
      'Eye Brooch',
      'Tikka',
      'Jhumar',
      'Nose Chain',
      'Hair Accessories',
      'Other Face Jewelry',
    ],
  },
  'Foot Wear': {
    'Men Formal Shoes': [
      'Men Formal Shoes',
    ],
    'Women Formal Shoes': [
      'Women Formal Shoes',
    ],
    'Kids Formal Shoes': [
      'Kids Formal Shoes',
    ],
    'Men Casual Shoes': [
      'Men Casual Shoes',
    ],
    'Women Casual Shoes': [
      'Women Casual Shoes',
    ],
    'Kids Casual Shoes': [
      'Kids Casual Shoes',
    ],
    'Men Sports Shoes': [
      'Men Sports Shoes',
    ],
    'Women Sports Shoes': [
      'Women Sports Shoes',
    ],
    'Kids Sports Shoes': [
      'Kids Sports Shoes',
    ],
    'Men Sandals': [
      'Men Sandals',
    ],
    'Women Sandals': [
      'Women Sandals',
    ],
    'Kids Sandals': [
      'Kids Sandals',
    ],
    'Men Slippers': [
      'Men Slippers',
    ],
    'Women Slippers': [
      'Women Slippers',
    ],
    'Kids Slippers': [
      'Kids Slippers',
    ],
    'Men Sneakers': [
      'Men Sneakers',
    ],
    'Women Sneakers': [
      'Women Sneakers',
    ],
    'Kids Sneakers': [
      'Kids Sneakers',
    ],
    'Men Ethnic Footwear': [
      'Men Ethnic Footwear',
    ],
    'Women Ethnic Footwear': [
      'Women Ethnic Footwear',
    ],
    'Kids Ethnic Footwear': [
      'Kids Ethnic Footwear',
    ],
    'Men Loafers': [
      'Men Loafers',
    ],
    'Women Loafers': [
      'Women Loafers',
    ],
    'Kids Loafers': [
      'Kids Loafers',
    ],
    'Men Mojaris': [
      'Men Mojaris',
    ],
    'Women Mojaris': [
      'Women Mojaris',
    ],
    'Kids Mojaris': [
      'Kids Mojaris',
    ],
    'Men Kolhapuri Chappals': [
      'Men Kolhapuri Chappals',
    ],
    'Women Kolhapuri Chappals': [
      'Women Kolhapuri Chappals',
    ],
    'Kids Kolhapuri Chappals': [
      'Kids Kolhapuri Chappals',
    ],
    'Men Juttis': [
      'Men Juttis',
    ],
    'Women Juttis': [
      'Women Juttis',
    ],
    'Kids Juttis': [
      'Kids Juttis',
    ],
    'Men Brogues': [
      'Men Brogues',
    ],
    'Women Brogues': [
      'Women Brogues',
    ],
    'Kids Brogues': [
      'Kids Brogues',
    ],
    'Men Chappals': [
      'Men Chappals',
    ],
    'Women Chappals': [
      'Women Chappals',
    ],
    'Kids Chappals': [
      'Kids Chappals',
    ],
  },
  'Home Decor & Furnishing': {
    'Home Furnishing': [
      'Bed Sheets',
      // 'Mattress Covers'
      'Fitted Bed Sheets & Blinds',
      'Curtains',
      'Curtains Accessoriess',
      'Pillows',
      'Pillow Covers',
      'Cushions',
      'Cushion Covers',
      'Furniture Covers',
      'Kids Beddings',
      'Fabrics',
      'Carpets',
      'Table Liners',
      'Bath Liners',
      'Floor Mats',
      'Dohads',
      'Quilts',
      'Blankets',
      'Diwan Sets',
      'Mattress Protectors',
      'Orthopedic Products',
      'Gifting',
      'Other Home Furnishing Products',
    ],
    'Home Decor': [
      'Table Top Decor',
      'Artificial Plants & Trees',
      'Artificial Flowers',
      'Vases',
      'Vase Fillers',
      'Planters',
      'Candles',
      'LED Candles',
      'Candle Holders',
      'Wall Decor',
      'Paintings',
      'Hangings',
      'Decorative Lights',
      'Figurines',
      'Show Pieces',
      'Wall Shelves',
      'Ethnic Wall Art',
      'Other Home Decor Products',
    ],
    'Spiritual Decor': [
      'Idols',
      'Home Temples',
      'Spiritual Themed Lights',
      'Toran',
      'Stickers',
      'Other Spiritual Decor Products',
    ],
    'Lights': [
      'Decorative Lights',
      'String Lights',
      'Chandeliers',
      'Wall Lamps',
      'Pendant Lights',
      'Home Lamps',
      'Light Fixtures',
      'Night Lamps',
      'Outdoor Lights',
      'Garden Lights',
      'Bulbs',
      'Essential Lights',
      'Other Lights',
    ],
  },
  'Art & Craft': {
    'Handcrafts': [
      'Pots',
      'Festive Handcrafts',
      'Woodwork',
      'Metalwork',
      'Threadwork',
      'Clothwork & Embroidery',
      'Other Handcrafts',
    ],
    'Art & Craft Supplies': [
      'Paper',
      'Crayons & Pastols',
      'Sketch Pen & Markers',
      'Drawing Books',
      'Scrap Books',
      'Paints & Brushes',
      'Canvas & Boards',
      'Glitters',
      'Adhesives & Glues',
      'Punches',
      'Threads & Wools',
      'Quillings',
      'Embossing',
      'Stencils',
      'Threads & Ribbon',
      'Card Making Kits',
      'Party Props & Supplies',
      'Gift Wrappings',
      'Knitting & Yarn Wools Essentials',
      'Beading & Jewelry Making Essentials',
      'Glue Guns',
      'Crafting Tools',
      'Other Art & Craft Supplies',
    ],
  },
  'Festive Essentials': {
    'Decorations': [
      'Rangoli colors',
      'Diyas (oil lamps)',
      'Torans (door hangings)',
      'Fairy lights',
      'Festive lanterns',
      'Decorative candles',
      'Festive tableware',
      'Wall hangings',
      'Flower garlands',
      'Paper decorations',
      'Puja Essentials',
      'Incense sticks',
      'Puja thali',
      'Camphor',
      'Kumkum',
      'Flowers',
      'Bells',
      'Holy books',
      'Sacred threads',
      'Conch shells',
      'Puja idols',
      'Gifts',
      'Dry fruit boxes',
      'Silver coins',
      'Gift hampers',
      'Cash envelopes',
      'Perfumes',
      'Home decor items',
      'Personalized gifts',
      'Gift cards',
      'Handicrafts',
      'Photo frames',
      'Miscellaneous',
      'Firecrackers',
      'Greeting cards',
      'Traditional music instruments',
      'Festive wrapping paper',
      'Seasonal plants',
      'Festive masks',
      'Henna (mehndi)',
      'Decorative baskets',
      'Umbrellas',
      'Cultural artifacts',
      'Marigold strings',
      'Decorative bells',
      'Tapestries',
      'Festive curtains',
      'Table runners',
      'Door beads',
      'Festive wall decals',
      'String lights with shapes',
      'Decorative plates',
      'Crystal hangings',
      'Other Decorations',
    ],
    'Puja Essentials': [
      'Clothing For Gods',
      'Incense sticks (Dhoop Agarbati)',
      'God Photos',
      'Puja thali',
      'Camphor',
      'Kumkum',
      'Flowers',
      'Bells',
      'Haldi Kumkum Karanda (Plate)',
      'Holy books',
      'Sacred threads (Moli)',
      'Conch shells',
      'Puja idols',
      'Brass lamps (Diya)',
      'Holy Containers (Puja Bartan)',
      'Sandalwood',
      'Kalash (Water Vessel)',
      'Ghee lamps',
      'Ritual conch (shankha)',
      'Puja mats',
      'Other Puja Essentials',
    ],
    'Gifts': [
      'Dry fruit boxes',
      'Silver coins',
      'Gift hampers',
      'Cash envelopes',
      'Perfumes',
      'Home decor items',
      'Personalized gifts',
      'Gift cards',
      'Handicrafts',
      'Photo frames',
      'Art prints',
      'Scented candles',
      'Spiritual books',
      'Customized jewelry boxes',
      'Traditional games',
      'Handmade soaps',
      'Aroma diffusers',
      'Meditation cushions',
      'Artistic pottery',
      'Other Gifts',
    ],
    'Miscellaneous': [
      'Firecrackers',
      'Greeting cards',
      'Traditional music instruments',
      'Festive wrapping paper',
      'Seasonal plants',
      'Festive masks',
      'Henna (mehndi)',
      'Decorative baskets',
      'Umbrellas',
      'Cultural artifacts',
      'Traditional puppets',
      'Ethnic dolls',
      'Decorative fans',
      'Cultural DVDs',
      'Traditional board games',
      'Storytelling books',
      'Ethnic musical CDs',
      'Cultural dance props',
      'Traditional masks',
      'Decorative umbrellas',
      'Other Miscellaneous Products',
    ],
    'Specific Festive Essentials': [
      'Diwali Essentials',
      'Holi Essentials',
      'Navratri Essentials',
      'Christmas Essentials',
      'Eid Essentials',
      'Baisakhi Essentials',
      'Makar Sankranti Essentials',
      'New Year Essentials',
      'Lohri Essentials',
      'Jain Festival Essentials',
      'Durga Puja Essentials',
      'Dussehra Essentials',
      'Ganesh Chaturthi Essentials',
      'Raksha Bandhan Essentials',
      'Pongal Essentials',
      'Onam Essentials',
      'Gudi Padwa Essentials',
      'Other Specific Festive Products',
    ],
  },
  "Baby Care": {
    "Baby Accessories": [
      "Baby Bottle",
      "Pacifier",
      "Baby Feeding Set",
      "Baby Bib",
      "Baby Feeding Spoon",
      "Baby Toothbrush",
      "Teething Necklace",
      "Nipple Shield",
      "Baby Bottle Warmer",
      "Sterilizer for Baby Bottles"
    ],
    "Baby Essentials": [
      "Diapers",
      "Baby Wipes",
      "Swaddle Blanket",
      "Baby Bath Towel",
      "Baby Carrier",
      "Diaper Bag",
      "Baby Nails Clipper",
      "Thermometer",
      "Baby Rash Cream",
      "Baby Lotion"
    ],
    "Baby Furnishing": [
      "Crib Mattress",
      "Baby Bedding Set",
      "Changing Pad",
      "Baby Crib",
      "Nursery Chair",
      "Playpen",
      "Crib Mobile",
      "Baby Sleeping Bag",
      "Rocking Chair",
      "Baby Blanket"
    ],
    "Baby Hair Care": [
      "Baby Shampoo",
      "Baby Hair Oil",
      "Baby Hair Comb",
      "Gentle Hair Brush",
      "Leave-in Hair Conditioner",
      "Baby Hair Detangler",
      "Baby Scalp Massager",
      "Hair Wash Mitt",
      "Organic Baby Hair Oil",
      "Baby Shampoo Bar"
    ],
    "Baby Skin Care": [
      "Baby Lotion",
      "Baby Soap",
      "Diaper Rash Cream",
      "Baby Oil",
      "Baby Cream",
      "Baby Sunscreen",
      "Baby Powder",
      "Baby Moisturizing Cream",
      "Baby Skincare Gift Set",
      "Organic Baby Body Butter"
    ],
    "Baby Toys": [
      "Stuffed Toy",
      "Rattle",
      "Teething Toy",
      "Play Gym",
      "Baby Swing",
      "Musical Toy",
      "Stacking Toy",
      "Interactive Toy",
      "Baby Activity Cube",
      "Toy Set for Newborns"
    ],
    "Baby Wear": [
      "Onesies",
      "Booties",
      "Hats",
      "Baby Romper",
      "Sleep Suit",
      "Baby Jacket",
      "Baby Socks",
      "Mittens",
      "Baby Dresses",
      "Baby Shoes"
    ],
    "Nappies": [
      "Disposable Nappies",
      "Cloth Nappies",
      "Eco-friendly Nappies",
      "Pull-Up Nappies",
      "Nighttime Nappies",
      "Swim Nappies",
      "Biodegradable Nappies",
      "Nappy Liners",
      "Training Pants",
      "Reusable Nappies"
    ]
  },
  "Cakes": {
    "Customized": [
      "Personalized Birthday Cake",
      "Wedding Cake",
      "Anniversary Cake",
      "Custom Logo Cake",
      "Photo Cake",
      "Themed Birthday Cake",
      "Bridal Shower Cake",
      "Baby Shower Cake",
      "Graduation Cake",
      "Retirement Cake"
    ],
    "Fruit": [
      "Strawberry Cake",
      "Mango Cake",
      "Mixed Berry Cake",
      "Blueberry Cheesecake",
      "Pineapple Cake",
      "Peach Cake",
      "Watermelon Cake",
      "Citrus Fruit Cake",
      "Banana Walnut Cake",
      "Apple Cinnamon Cake"
    ],
    "Modern": [
      "Mirror Glaze Cake",
      "Geode Cake",
      "Bomb Cake",
      "Drip Cake",
      "Galaxy Cake",
      "Rainbow Cake",
      "Unicorn Cake",
      "Gold Leaf Cake",
      "3D Sculpture Cake"
    ],
    "Theme": [
      "Superhero Cake",
      "Princess Cake",
      "Harry Potter Cake",
      "Pirate Ship Cake",
      "Cars Cake",
      "Frozen Cake",
      "Minecraft Cake",
      "Spiderman Cake",
      "Barbie Cake",
      "Farm Animal Cake"
    ]
  },
  "Electronics": {
    "Educational": [
      "STEM Learning Kit",
      "Solar Powered Calculator",
      "Educational Tablet",
      "Math & Science Experiment Kit",
      "Interactive Whiteboard",
      "Smart Learning Globe",
      "Electric Circuit Kit",
      "Robotics Kit",
      "Language Learning Headphones",
      "Coding Robot"
    ],
    "Home": [
      "Smart TV",
      "Bluetooth Speaker",
      "Air Purifier",
      "Robot Vacuum Cleaner",
      "Smart Light Bulbs",
      "Electric Heater",
      "Soundbar",
      "Refrigerator",
      "Smart Plug",
      "Electric Fan"
    ],
    "Kitchen": [
      "Electric Kettle",
      "Juicer Blender",
      "Microwave Oven",
      "Rice Cooker",
      "Toaster",
      "Coffee Maker",
      "Food Processor",
      "Induction Cooktop",
      "Smart Fridge",
      "Water Purifier"
    ],
    "Office": [
      "Laptop",
      "Wireless Mouse",
      "Printer",
      "Keyboard",
      "Desk Lamp",
      "Document Scanner",
      "Shredder",
      "Office Chair",
      "Projector",
      "External Hard Drive"
    ],
    "Personal": [
      "Smartwatch",
      "Fitness Tracker",
      "Wireless Earbuds",
      "Bluetooth Headphones",
      "Smart Glasses",
      "Portable Power Bank",
      "E-Reader",
      "Electronic Nail Care Kit",
      "Electric Toothbrush",
      "Massage Gun"
    ]
  },
  "Kitchen Essentials": {
    "Cleaners": [
      "All-Purpose Cleaner",
      "Glass Cleaner",
      "Dishwashing Liquid",
      "Kitchen Surface Sanitizer",
      "Oven Cleaner",
      "Stainless Steel Cleaner",
      "Dishwasher Detergent",
      "Disinfectant Wipes",
      "Grease Remover",
      "Wood Cleaner"
    ],
    "Containers": [
      "Plastic Food Storage Containers",
      "Glass Storage Jars",
      "Stainless Steel Food Containers",
      "Airtight Storage Boxes",
      "Lunch Box Containers",
      "Freezer Safe Containers",
      "Spice Containers",
      "Drawer Organizers",
      "Food Canisters",
      "Baking Storage Containers"
    ],
    "Cookware": [
      "Non-Stick Frying Pan",
      "Pressure Cooker",
      "Cookware Set",
      "Saucepan",
      "Griddle Pan",
      "Baking Tray",
      "Roasting Pan",
      "Wok",
      "Dutch Oven",
      "Cast Iron Skillet"
    ],
    "Crockery": [
      "Dinner Plates",
      "Side Plates",
      "Soup Bowls",
      "Serving Platters",
      "Cups and Saucers",
      "Bowls Set",
      "Chopsticks",
      "Soup Mugs",
      "Salad Plates",
      "Platters"
    ],
    "Glassware": [
      "Champagne Flutes",
      "Beer Mugs",
      "Water Glasses",
      "Juice Glasses",
      "Tumblers",
      "Whiskey Glasses",
      "Tea Glasses",
      "Cocktail Glasses",
      "Shot Glasses"
    ],
    "Grocery": [
      "Rice",
      "Pulses",
      "Flour",
      "Sugar",
      "Spices",
      "Cooking Oil",
      "Tea",
      "Coffee",
      "Salt",
      "Instant Noodles"
    ],
    "Kitchen Decor": [
      "Wall Clocks",
      "Decorative Trays",
      "Table Mats",
      "Placemat Sets",
      "Wall Art",
      "Table Centerpiece",
      "Storage Baskets",
      "Pot Holders",
      "Decorative Bowls",
      "Salt and Pepper Shakers"
    ],
    "Kitchen Napkins": [
      "Cotton Napkins",
      "Linen Napkins",
      "Paper Napkins",
      "Dinner Napkins",
      "Tea Towels",
      "Dish Cloths",
      "Reusable Napkins",
      "Printed Napkins",
      "Embossed Napkins",
      "Fancy Napkins"
    ],
    "Kitchen Organizers": [
      "Spice Rack",
      "Utensil Holder",
      "Pantry Organizers",
      "Cutlery Organizer",
      "Drawer Dividers",
      "Fridge Organizer",
      "Cupboard Organizers",
      "Bread Box",
      "Jar Organizers",
      "Under-Sink Organizers"
    ],
    "Organizers": [
      "Drawer Organizer Trays",
      "Shelf Organizers",
      "Pantry Storage Bins",
      "Countertop Organizers",
      "Pull-Out Racks",
      "Wall-Mounted Organizers",
      "Under-Sink Storage",
      "Kitchen Cart",
      "Cutlery Tray",
      "Cabinet Organizers"
    ],
    "Plasticware": [
      "Plastic Storage Containers",
      "Plastic Water Bottles",
      "Plastic Cutting Boards",
      "Plastic Lunch Boxes",
      "Plastic Cups",
      "Plastic Pitcher",
      "Plastic Measuring Cups",
      "Plastic Food Covers",
      "Plastic Bins",
      "Plastic Waste Bins"
    ],
    "Serveware": [
      "Serving Platters",
      "Serving Bowls",
      "Salad Servers",
      "Gravy Boat",
      "Serving Tongs",
      "Cake Stand",
      "Cheese Board",
      "Snack Bowls",
      "Chip and Dip Tray",
      "Soup Ladle"
    ],
    "Tools": [
      "Whisk",
      "Peeler",
      "Tongs",
      "Bottle Opener",
      "Grater",
      "Slicing Knife",
      "Can Opener",
      "Mandoline Slicer",
      "Garlic Press"
    ],
    "Utensils": [
      "Spoons Set",
      "Forks Set",
      "Knives Set",
      "Spatula Set",
      "Ladles",
      "Slotted Spoon",
      "Soup Spoon",
      "Chopping Knife",
      "Serving Spoon"
    ],
    "Woodenware": [
      "Wooden Cutting Board",
      "Wooden Spoon Set",
      "Wooden Salad Servers",
      "Wooden Tray",
      "Wooden Bowls",
      "Wooden Rolling Pin",
      "Wooden Ladle",
      "Wooden Tongs",
      "Wooden Pepper Mill",
    ]
  },
  "Stationery": {
    "Drawing": [
      "Sketch Pencils",
      "Color Pencils",
      "Oil Pastels",
      "Watercolors",
      "Acrylic Paints",
      "Drawing Paper",
      "Canvas",
      "Markers",
      "Coloring Book",
      "Erasers"
    ],
    "Educational Books": [
      "Mathematics Workbook",
      "Science Encyclopedia",
      "English Grammar Book",
      "History Textbook",
      "Geography Atlas",
      "Dictionary",
      "Puzzle Books",
      "Interactive Learning Books",
      "Spelling Books",
      "Creative Writing Books"
    ],
    "School Bag": [
      "Backpack",
      "Messenger Bag",
      "Trolley Bag",
      "Laptop Backpack",
      "School Rucksack",
      "Padded School Bag",
      "Lunch Box Bag",
      "Bag with Water Bottle Holder",
      "Canvas School Bag",
      "School Travel Bag"
    ],
    "School Essentials": [
      "Lunch Box",
      "Water Bottle",
      "Pencil Case",
      "Ruler",
      "Sharpener",
      "Notebook",
      "Pen Set",
      "Highlighter",
      "Glue Stick",
      "Folder"
    ],
    "Writing": [
      "Ballpoint Pens",
      "Gel Pens",
      "Fountain Pens",
      "Mechanical Pencils",
      "Ink Refills",
      "Erasable Pens",
      "Markers",
      "Chalk",
      "Colored Pencils",
      "Brush Pens"
    ]
  },
  "Travel & Bags": {
    "Baskets": [
      "Wicker Basket",
      "Storage Basket",
      "Laundry Basket",
      "Picnic Basket",
      "Fruit Basket",
      "Collapsible Storage Basket",
      "Gift Basket",
      "Organizer Basket",
      "Plastic Storage Basket",
      "Seagrass Basket"
    ],
    "Duffel Bags": [
      "Canvas Duffel Bag",
      "Leather Duffel Bag",
      "Sports Duffel Bag",
      "Travel Duffel Bag",
      "Foldable Duffel Bag",
      "Waterproof Duffel Bag",
      "Weekend Duffel Bag",
      "Military Duffel Bag",
      "Gym Duffel Bag",
      "Duffel Bag with Shoe Compartment"
    ],
    "Picnic Bags": [
      "Insulated Picnic Bag",
      "Picnic Backpack",
      "Cooler Picnic Bag",
      "Wicker Picnic Basket",
      "Lunch Cooler Bag",
      "Portable Picnic Bag",
      "Thermal Picnic Bag",
      "Picnic Blanket Bag",
      "Picnic Cooler Backpack",
      "Lunch Tote"
    ],
    "Purse": [
      "Leather Purse",
      "Clutch Purse",
      "Wallet Purse",
      "Crossbody Purse",
      "Small Evening Purse",
      "Beaded Purse",
      "Zipper Purse",
      "Chain Handle Purse",
      "Sling Purse",
      "Canvas Purse"
    ],
    "Shopping Bags": [
      "Reusable Shopping Bags",
      "Tote Bags",
      "Foldable Shopping Bag",
      "Eco-Friendly Shopping Bags",
      "Jute Shopping Bags",
      "Collapsible Shopping Bag",
      "Grocery Shopping Bag",
      "Insulated Shopping Bag",
      "Custom Printed Shopping Bag",
      "Cotton Shopping Bag"
    ],
    "Travel Bags": [
      "Hard Shell Travel Bag",
      "Soft Case Travel Bag",
      "Carry-On Travel Bag",
      "Rolling Travel Bag",
      "Laptop Travel Bag",
      "Lightweight Travel Bag",
      "Expandable Travel Bag",
      "Fashionable Travel Bag",
      "Travel Duffel Bag",
      "Waterproof Travel Bag"
    ],
    "Travel Storage Bags": [
      "Compression Travel Storage Bags",
      "Garment Travel Bags",
      "Travel Organizer Bags",
      "Foldable Travel Storage Bags",
      "Packing Cubes",
      "Shoe Storage Bags",
      "Toiletry Travel Bag",
      "Under Bed Travel Storage Bags",
      "Cosmetic Travel Organizer",
      "Clothing Storage Bag"
    ],
    "Wallets": [
      "Leather Wallet",
      "Card Holder Wallet",
      "Bifold Wallet",
      "Trifold Wallet",
      "Money Clip Wallet",
      "Coin Wallet",
      "Zip Wallet",
      "Travel Wallet",
      "Slim Wallet",
      "Wallet with RFID Protection"
    ],
    "Women Bags": [
      "Tote Bag",
      "Clutch Bag",
      "Hobo Bag",
      "Bucket Bag",
      "Satchel Bag",
      "Crossbody Bag",
      "Shoulder Bag",
      "Handbag",
      "Backpack Purse",
      "Evening Bag"
    ]
  },
};
