Map<String, Map<String, String>> householdSubCategories = {
  'Fashion & Clothing': {
    'Men Wear': '',
    'Accessories For Men': '',
    'Women Wear': '',
    'Accessories For Women': '',
    'Kids Wear': '',
    'Accessories For Kids': '',
  },
  'Food': {
    'Daily Needs': '',
    'Ready To Eat Food': '',
    'Bakery Items': '',
    'Namkeen': '',
    'Snacks': '',
    'Baked & Roasted Snacks': '',
    'Chaat': '',
    'Starters': '',
    'Main Course': '',
    'Gujarati Food': '',
    'Punjabi Food': '',
    'Maharashtrian Food': '',
    'South Indian Food': '',
    'Wester Food': '',
    'Sweets & Desserts': '',
    'Beverages': '',
  },
  'Beauty & Care': {
    'Face': '',
    'Eyes': '',
    'Lips': '',
    'Beard': '',
    'Tools & Accessories': '',
    'Hair Care & Styling': '',
    'Skin Care': '',
  },
  'Home Essentials': {
    'Cleaners': '',
    'Cleaning Tools': '',
  },
  'Health Care': {
    'Ayurvedic Products': '',
    'Homeopathy': '',
    'Personal Care': '',
    'Sports Supplements': '',
    'Diet & Nutrition': '',
    'Health Care Devices': '',
  },
  'Jewelry': {
    'Neck': '',
    'Legs': '',
    'Hand': '',
    'Face': '',
  },
  'Foot Wear': {
    'Men': '',
    'Women': '',
    'Kids': '',
  },
  'Home Decor & Furnishing': {
    'Home Furnishing': '',
    'Home Decor': '',
    'Spiritual Decor': '',
    'Lights': '',
  },
  'Art & Craft': {
    'Handcrafts': '',
    'Art & Craft Supplies': '',
  },
  'Festive Essentials': {
    'Decorations': '',
    'Puja Essentials': '',
    'Gifts': '',
    'Miscellaneous': '',
    'Specific Festive Essentials': '',
  },
};
