// // Name, Hint Text, No of Answers, Dropdown Items, TextInputType, Max Lines, Mandatory Info
// final Map<String, Map<String, Map<String, dynamic>>>
//     householdCategoryProperties = {
//   // fashion & clothing: 1
//   // food: 1
//   // health care: 3
//   // jewelry: 1
//   'Art & Craft': {
//     'Type': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Painting', 'Drawing', 'Sculpture', 'Craft', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Canvas', 'Paper', 'Clay', 'Wood', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size (in cm)': {
//       'hintText': 'eg. 80cm X 20cm',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Blue',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Techniques Used': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': [
//         'Acrylic',
//         'Oil Painting',
//         'Watercolor',
//         'Digital',
//         'Other'
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Artist Name': {
//       'hintText': 'Name of Artist',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Baby Care': {
//     '0': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Diapers', 'Baby Food', 'Clothing', 'Toys', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Gender': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Male', 'Female'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Age Group': {
//       'hintText': 'eg. 0-6 months, 6-12 months',
//       'noOfAnswers': 2,
//       'dropDownItems': ['0-6 months', '6-12 months', '1-2 years', '3+ years'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': 'eg. Cotton, Plastic',
//       'noOfAnswers': 1,
//       'dropDownItems': ['Cotton', 'Plastic', 'Silicone', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'Custom'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Safety Certifications': {
//       'hintText': 'eg. BIS, FDA Approved, None',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Beauty & Care': {
//     'Product Type': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': [
//         'Skincare',
//         'Haircare',
//         'Makeup',
//         'Personal Hygiene',
//         'Other'
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '0': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'Extra Large', 'Custom'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Blue',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Ingredients': {
//       'hintText': 'eg. Rose Water, Vitamin C',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 3,
//       'compulsory': false,
//     },
//     'Usage Instructions': {
//       'hintText': 'How To Use, Safety Instructions',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Cakes': {
//     'Flavor': {
//       'hintText': 'eg. Chocolate, Vanilla',
//       'noOfAnswers': 1,
//       'dropDownItems': [
//         'Chocolate',
//         'Vanilla',
//         'Strawberry',
//         'Butterscotch',
//         'Other',
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '0': {
//       'hintText': 'eg. Chocolate, Vanilla',
//       'noOfAnswers': 1,
//       'dropDownItems': [
//         'Chocolate',
//         'Vanilla',
//         'Strawberry',
//         'Butterscotch',
//         'Other',
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': 'eg. 250g, 500g (in grams)',
//       'noOfAnswers': 1,
//       'dropDownItems': ['500g', '1kg', '2kg', 'Custom'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Shape': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Round', 'Square', 'Heart', 'Custom'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Eggless': {
//       'hintText': 'Yes/No',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Yes', 'No'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Occasion': {
//       'hintText': 'eg. Birthday, Anniversary',
//       'noOfAnswers': 1,
//       'dropDownItems': [
//         'Birthday',
//         'Anniversary',
//         'Wedding',
//         'Festival',
//         'Other',
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Electronics': {
//     '0': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Mobile', 'Laptop', 'Tablet', 'Appliance', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Storage': {
//       'hintText': 'eg. 128, 256, 512 (in gb)',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 1,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'RAM': {
//       'hintText': 'eg. 6, 8, 12 (in gb)',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 1,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Colors': {
//       'hintText': 'eg. Blue, Black',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Warranty': {
//       'hintText': 'eg. 1 Year, 2 Years (in years)',
//       'noOfAnswers': 1,
//       'dropDownItems': ['6 months', '1 Year', '2 Years', 'No Warranty'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Features': {
//       'hintText': 'eg. Fingerprint Sensor, 8GB RAM',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 3,
//       'compulsory': false,
//     },
//   },

//   'Fashion & Clothing': {
//     'Category': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Men\'s', 'Women\'s', 'Kids', 'Unisex'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Quantity': {
//       'hintText': 'eg. 1 set',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Blue',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': ['Cotton', 'Polyester', 'Silk', 'Wool', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '0': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Festive Essentials Products': {
//     'Category': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': [
//         'Decorations',
//         'Clothing',
//         'Accessories',
//         'Gifts',
//         'Party Supplies'
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Quantity': {
//       'hintText': 'eg. set of 3, set of 5',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 1,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'One Size'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Gold',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': ['Paper', 'Fabric', 'Plastic', 'Metal', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Occasion': {
//       'hintText': 'eg. Diwali, Christmas, Eid, Others',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Food': {
//     'Flavor Profile': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': ['Sweet', 'Savory', 'Spicy', 'Sour', 'Bitter', 'Umami'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Quantity': {
//       'hintText': 'eg. 500g, 1L',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 1,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Expiry Duration': {
//       'hintText': 'eg. 1 month, 6 months',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 2,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Packaging Type': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': [
//         'Box',
//         'Bag',
//         'Can',
//         'Bottle',
//         'Jar',
//         'Pouch',
//         'Packet'
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Serving Size': {
//       'hintText': 'eg. 100g, 1 cup',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '0': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Foot Wear': {
//     'Size': {
//       'hintText': 'eg. UK 5, US 7',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Black, Brown',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': [
//         'Leather',
//         'Suede',
//         'Canvas',
//         'Synthetic',
//         'Rubber',
//         'Other'
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Closure Type': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': ['Lace-Up', 'Slip-On', 'Velcro', 'Zipper', 'Buckle'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Heel Height': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': ['Flat', 'Low', 'Medium', 'High'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Health Care ': {
//     'Expiry Duration': {
//       'hintText': 'eg, 1 month, 6 month',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 2,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Usage Instructions': {
//       'hintText': 'eg. Apply twice daily',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Precautions': {
//       'hintText': 'e.g Avoid contact with eyes',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '0': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '1': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '2': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Home Decor & Furnishing': {
//     'Color': {
//       'hintText': 'e.g Beige, Gray',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Wood', 'Metal', 'Glass', 'Fabric', 'Leather', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Assembly Required': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Yes', 'No'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size (in cm)': {
//       'hintText': 'e.g 80cm X 100cm X 20cm',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Pattern': {
//       'hintText': 'e.g Floral, Geometric',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Care Instructions': {
//       'hintText': 'eg.  Wipe with a damp cloth',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Cleaning Essentials': {
//     'Color': {
//       'hintText': 'eg. Beige, Grey',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': 'eg. Cotton, Wood',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'Custom'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Usage': {
//       'hintText': 'eg. Daily Use, Occasional Use',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Features': {
//       'hintText': 'eg. Waterproof, Foldable',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Maintenance': {
//       'hintText': 'eg. Easy to Clean, Requires Special Care',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Jewelry': {
//     'Material': {
//       'hintText': 'eg. Gold, Silver',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Gold, Silver, Rose Gold',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'Adjustable'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Occasion': {
//       'hintText': 'e.g., Wedding, Casual, Party',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Care Instructions': {
//       'hintText': 'e.g., Clean with a soft cloth, Avoid contact with chemicals',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '0': {
//       'hintText': '',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Kitchen Essentials': {
//     '0': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Utensils', 'Appliances', 'Storage', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Electric': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Yes', 'No'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Set': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Yes', 'No'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': 'eg. Steel, Plastic',
//       'noOfAnswers': 1,
//       'dropDownItems': ['Steel', 'Plastic', 'Glass', 'Wood', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': 'eg. Small, Medium, Large',
//       'noOfAnswers': 3,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'Custom'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Blue',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Stationery': {
//     '0': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Set': {
//       'hintText': 'eg. Cello, Camlin',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Yes', 'No'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '1': {
//       'hintText': 'eg. Cello, Camlin',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': 'eg. Paper, Plastic',
//       'noOfAnswers': 1,
//       'dropDownItems': ['Paper', 'Plastic', 'Metal', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Blue',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': 'eg. A4, A5',
//       'noOfAnswers': 1,
//       'dropDownItems': ['A4', 'A5', 'Custom'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Travel & Bags': {
//     '0': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Backpack', 'Suitcase', 'Handbag', 'Wallet', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '1': {
//       'hintText': '',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Backpack', 'Suitcase', 'Handbag', 'Wallet', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': 'eg. Leather, Nylon',
//       'noOfAnswers': 2,
//       'dropDownItems': ['Leather', 'Nylon', 'Polyester', 'Plastic', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': 'eg. Small, Medium, Large',
//       'noOfAnswers': 3,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'Extra Large'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Blue',
//       'noOfAnswers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Compartments': {
//       'hintText': 'eg. 1, 2',
//       'noOfAnswers': 1,
//       'dropDownItems': [],
//       'inputType': 1,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
// };
