Map<String, Map<String, List<String>>> householdSpecialCategories = {
  'Fashion & Clothing': {
    'Men Wear': [
      'Shirts',
      'T - Shirts',
      'Polos',
      'Trousers',
      'Jeans',
      'Night Wear',
      'Winter Wear',
      'Jackets',
      'Suits',
      'Active Wear',
      'Hats',
      'Scarves',
      'Belts',
      'Masks',
      'Gloves',
      'Tie',
      'Socks',
      'Foot Wear',
      'Formal Wear',
      'Party Wear',
      'Wedding Attire',
      'Coats',
      'Rain Wear',
      'Blazers',
      'Bottoms',
      'Kurta Pajama',
      'Sherwani',
      'Hoodies',
    ],
    'Accessories For Men': [
      'Scarves',
      'Masks',
      'Gloves',
      'Tie',
      'Hats',
      'Socks',
      'Belts',
      'Bags',
      'Wallets',
      'Watches',
    ],
    'Women Wear': [
      'Shirts',
      'T - Shirts',
      'Polos',
      'Trousers',
      'Saree',
      'Kurta Sets',
      'Ghagra Choli',
      'party Gowns',
      'Lehenga',
      'Punjabi Dress',
      'Dresses',
      'Night Wear',
      'Winter Wear',
      'Skirts',
      'Jackets',
      'Jeans',
      'Suits',
      'Active Wear',
      'Hats',
      'Scarves',
      'Belts',
      'Masks',
      'Gloves',
      'Tie',
      'Socks',
      'Foot Wear',
      'Formal Wear',
      'Party Wear',
      'Wedding Attire',
      'Coats',
      'Rain Wear',
      'Blazers',
    ],
    'Accessories For Women': [
      'Scarves',
      'Dupatta',
      'Masks',
      'Gloves',
      'Tie',
      'Hats',
      'Socks',
      'Belts',
      'Bags',
      'Purses',
      'Watches',
    ],
    'Kids Wear': [
      'Shirts',
      'T - Shirts',
      'Polos',
      'Trousers',
      'Dresses',
      'Night Wear',
      'Winter Wear',
      'Skirts',
      'Jackets',
      'Jeans',
      'Suits',
      'Active Wear',
      'Hats',
      'Scarves',
      'Belts',
      'Masks',
      'Gloves',
      'Tie',
      'Socks',
      'Foot Wear',
      'Formal Wear',
      'Party Wear',
      'Wedding Attire',
      'Coats',
      'Rain Wear',
      'Blazers',
    ],
    'Accessories For Kids': [
      'Scarves',
      'Masks',
      'Gloves',
      'Tie',
      'Hats',
      'Socks',
      'Belts',
      'Bags',
      'Wallets',
      'Watches',
      'Purses',
    ],
  },
  'Food': {
    'Daily Needs': [
      'Fruits',
      'Vegetables',
      'Milk & Other Dairy Products',
      'Grains',
      'Cereals',
      'Rice',
      'Beverages',
      'Condiments',
      'Ice Creams & Other Frozen Foods',
      'Juices & Shakes',
      'Spices',
      'Herbs',
      'Oils',
      'Nuts',
      'Seeds',
    ],
    'Ready To Eat Food': [
      'Baked Food',
      'Canned Food',
      'Packet Food',
      'Frozen Food',
      'Festive Special Food',
      'Indian Snacks',
      'Dry Snacks',
      'Roti & Sabji',
      'Thali',
      'Dal & Rice',
      'Gujarati Food',
      'Punjabi Food',
      'Rajasthani Food',
      'South Indian',
      'North Indian',
      'Sweets',
      'Cakes & Bakery Items',
      'Western',
      'Chinese',
    ],
    'Bakery Items': [
      'Bread',
      'Muffins',
      'Pizza Base',
      'Cookies',
      'Biscuits',
      'Cakes',
      'Pastries',
      'Donuts',
      'Brownies',
      'Cupcakes',
      'Buns',
    ],
  },
  // 'Woodwork': {
  //   'Furniture': '',
  //   'Cabinets': '',
  //   'Shelves': '',
  //   'Tables': '',
  //   'Chairs': '',
  //   'Doors': '',
  //   'Windows': '',
  //   'Picture Frames': '',
  //   'Carvings': '',
  //   'Wooden Toys': '',
  //   'Cutting Boards': '',
  //   'Utensils': '',
  //   'Boxes': '',
  //   'Sculptures': '',
  //   'Decor': '',
  //   'Panels': '',
  //   'Flooring': '',
  //   'Signs': '',
  //   'Instruments': '',
  //   'Jewelry': '',
  // },

  // 'Metalwork': {
  //   'Art': '',
  //   'Sculptures': '',
  //   'Furniture': '',
  //   'Decor': '',
  //   'Jewelry': '',
  //   'Utensils': '',
  //   'Tools': '',
  //   'Supplies': '',
  //   'Sheets': '',
  //   'Pipes': '',
  //   'Fasteners': '',
  //   'Hardware': '',
  //   'Fixtures': '',
  //   'Components': '',
  //   'Casting': '',
  //   'Forging': '',
  //   'Engraving': '',
  //   'Finishing': '',
  //   'Plating': '',
  //   'Alloys': '',
  // },
  'Beauty & Care': {
    'Makeup': [
      'Lipsticks',
      'Foundation',
      'Mascara',
      'Eye Shadow',
      'Eye Liner',
      'Eye Creams',
      'Blush',
      'Highlighter',
      'Bronzer',
      'Makeup Remover',
      'Makeup Brushes',
      'Perfumes',
      'Skincare Products',
      'Moisturizers',
      'Serums',
      'Facial Cleansers',
      'Toners',
      'Face Masks',
      'Lip Balms',
      'Shampoo',
      'Conditioner',
      'Hair Color',
      'Hair Care Products',
      'Hair Styling Products',
      'Nail Polish',
      'Nail Care Products',
    ],
  },
  'Home Essentials': {
    // home decor, garden & outdoor, handloom & handicrafts, furniture, cleaning,
    '': [
      'Scented ',
      'Pillar ',
      'Jar ',
      'Tealight ',
      'Floating ',
      'Votive ',
      'Taper ',
      'Beeswax ',
      'Handmade ',
      'Decorative ',
      'Seasonal ',
      'Aromatherapy ',
      'Emergency ',
      'Candle Holders',
      'Candle Accessories',
      'Candle Making Supplies',
      'Wax Melts',
      'Incense Sticks',
      'Room Sprays',
    ],
  },
  'Health Care': {
    // ayurveda, homeopathy, personal care, sports supplements, diet & nutrition, health care devices, sports suppliments, offers and
    'Ayurvedic Products': [
      'Medicine',
      'Herbal Supplements',
      'Skincare',
      'Hair Care',
      'Massage Oils',
      'Teas',
      'Personal Care',
      'Digestive Aids',
      'Immune Boosters',
      'Joint Care',
      'Weight Management',
      'Dental Care',
      'Cosmetics',
      'Bath Products',
      'Essential Oils',
      'Health Tonics',
      'Herbal Extracts',
      'Stress Relief',
      'Anti-Aging Products',
      'Beauty Supplements',
    ],
  },
  // 'Papercraft': {
  //   'Greeting Cards': '',
  //   'Origami': '',
  //   'Scrapbooking Supplies': '',
  //   'Paper Quilling': '',
  //   'Paper Models': '',
  //   'Decoupage': '',
  //   'Card Making Supplies': '',
  //   'Paper Cutting': '',
  //   'Embossing Tools': '',
  //   'Paper Sculpture': '',
  //   'Paper Flowers': '',
  //   'Bookbinding Kits': '',
  //   'Paper Mache': '',
  //   'Papercraft Tools': '',
  //   'Stationery': '',
  //   'Paper Beads': '',
  //   'Paper Art Kits': '',
  //   'Paper Stickers': '',
  //   'Paper Craft Books': '',
  //   'DIY Paper Projects': '',
  // },
  'Jewelry': {
    // piercings, neck, face, hand, legs,
    '': [
      'Rings',
      'Necklaces',
      'Earrings',
      'Bracelets',
      'Anklets',
      'Brooches',
      'Pendants',
      'Chains',
      'Bangles',
      'Charms',
      'Jewelry Sets',
      'Men\'s Jewelry',
      'Women\'s Jewelry',
      'Children\'s Jewelry',
      'Fine Jewelry',
      'Fashion Jewelry',
      'Handmade Jewelry',
      'Wedding Jewelry',
      'Ethnic Jewelry',
      'Body Jewelry',
      'Custom Jewelry',
    ],
  },
  'Foot Wear': {},
  'Home Decor & Furnishing': {
    'Home Furnishing': [
      'Bed Sheets',
      // 'Mattress Covers'
      'Fitted Bed Sheets & Blinds',
      'Curtains',
      'Curtains Accessoriess',
      'Pillows',
      'Pillow Covers',
      'Cushions',
      'Cushion Covers',
      'Furniture Covers',
      'Kids Beddings',
      'Fabrics',
      'Carpets',
      'Table Liners',
      'Bath Liners',
      'Floor Mats',
      'Dohads',
      'Quilts',
      'Blankets',
      'Diwan Sets',
      'Mattress Protectors',
      'Orthopedic Products',
      'Gifting',
      'Others',
    ],
    'Home Decor': [
      'Table Top Decor',
      'Artificial Plants & Trees',
      'Artificial Flowers',
      'Vases',
      'Vase Fillers',
      'Planters',
      'Candles',
      'LED Candles',
      'Candle Holders',
      'Wall Decor',
      'Paintings',
      'Hangings',
      'Decorative Lights',
      'Figurines',
      'Show Pieces',
      'Wall Shelves',
      'Ethnic Wall Art',
      'Others',
    ],
    'Spiritual Decor': [
      'Idols',
      'Home Temples',
      'Spiritual Themed Lights',
      'Toran',
      'Stickers',
      'Others',
    ],
    'Lights': [
      'Decorative Lights',
      'String Lights',
      'Chandeliers',
      'Wall Lamps',
      'Pendant Lights',
      'Home Lamps',
      'Light Fixtures',
      'Night Lamps',
      'Outdoor Lights',
      'Garden Lights',
      'Bulbs',
      'Essential Lights',
      'Others',
    ],
  },
  'Art & Craft': {
    'Handcrafts': [
      'Pots',
      'Festive Handcrafts',
      'Woodwork',
      'Metalwork',
      'Threadwork',
      'Clothwork & Embroidery',
      '',
      '',
      '',
      '',
      '',
    ],
    'Art & Craft Supplies': [
      'Paper',
      'Crayons & Pastols',
      'Sketch Pen & Markers',
      'Drawing Books',
      'Scrap Books',
      'Paints & Brushes',
      'Canvas & Boards',
      'Glitters',
      'Adhesives & Glues',
      'Punches',
      'Threads & Wools',
      'Quillings',
      'Embossing',
      'Stencils',
      'Threads & Ribbon',
      'Card Making Kits',
      'Party Props & Supplies',
      'Gift Wrappings',
      'Knitting & Yarn Wools Essentials',
      'Beading & Jewelry Making Essentials',
      'Glue Guns',
      'Crafting Tools',
      'Others',
    ],
  },
  'Festive Essentials': {
    'Diwali': [
      'Decorative Lights',
      'String Lights',
      'Lanterns',
      'Holders',
      'Garlands',
      'Ornaments',
      'Christmas Trees',
      'Wreaths',
      'Tableware',
      'Party Decorations',
      'Gift Wrapping Supplies',
      'Holiday Cards',
      'Festive Clothing',
      'Seasonal Foods',
      'Fireworks',
      'Home Fragrances',
      'Holiday Music',
      'DIY Craft Kits',
      'Cultural Decorations',
      'Customized Gifts',
    ],
  }
};
