// // Name, Hint Text, No of Answers, Dropdown Items, TextInputType, Max Lines, Mandatory Info
// final Map<String, Map<String, Map<String, dynamic>>>
//     householdCategoryProperties = {
//   // fashion & clothing: 1
//   // food: 1
//   // health care: 3
//   // jewelry: 1
//   'Art & Craft': {
//     'Type': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': ['Painting', 'Drawing', 'Sculpture', 'Craft', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Material': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': ['Canvas', 'Paper', 'Clay', 'Wood', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Size (in cm)': {
//       'hintText': 'eg. 80cm X 20cm',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Blue',
//       'noOfAsnwers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Techniques Used': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': [
//         'Acrylic',
//         'Oil Painting',
//         'Watercolor',
//         'Digital',
//         'Other'
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Artist Name': {
//       'hintText': 'Name of Artist',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Beauty & Care': {
//     'Product Type': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': [
//         'Skincare',
//         'Haircare',
//         'Makeup',
//         'Personal Hygiene',
//         'Other'
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     '0': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'Extra Large', 'Custom'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Blue',
//       'noOfAsnwers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Ingredients': {
//       'hintText': 'eg. Rose Water, Vitamin C',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 3,
//       'compulsory': false,
//     },
//     'Usage Instructions': {
//       'hintText': 'How To Use, Safety Instructions',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Fashion & Clothing': {
//     'Category': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': ['Men\'s', 'Women\'s', 'Kids', 'Unisex'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Quantity': {
//       'hintText': 'eg. 1 set',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Blue',
//       'noOfAsnwers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': ['Cotton', 'Polyester', 'Silk', 'Wool', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '0': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Festive Essentials Products': {
//     'Category': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': [
//         'Decorations',
//         'Clothing',
//         'Accessories',
//         'Gifts',
//         'Party Supplies'
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Quantity': {
//       'hintText': 'eg. set of 3, set of 5',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 1,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'One Size'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Red, Gold',
//       'noOfAsnwers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Material': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': ['Paper', 'Fabric', 'Plastic', 'Metal', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Occasion': {
//       'hintText': 'eg. Diwali, Christmas, Eid, Others',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Food': {
//     'Flavor Profile': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': ['Sweet', 'Savory', 'Spicy', 'Sour', 'Bitter', 'Umami'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Quantity': {
//       'hintText': 'eg. 500g, 1L',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 1,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Expiry Duration': {
//       'hintText': 'eg. 1 month, 6 months',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 2,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Packaging Type': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': [
//         'Box',
//         'Bag',
//         'Can',
//         'Bottle',
//         'Jar',
//         'Pouch',
//         'Packet'
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Serving Size': {
//       'hintText': 'eg. 100g, 1 cup',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '0': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Foot Wear': {
//     'Size': {
//       'hintText': 'eg. UK 5, US 7',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Color': {
//       'hintText': 'eg. Black, Brown',
//       'noOfAsnwers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Material': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': [
//         'Leather',
//         'Suede',
//         'Canvas',
//         'Synthetic',
//         'Rubber',
//         'Other'
//       ],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Closure Type': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': ['Lace-Up', 'Slip-On', 'Velcro', 'Zipper', 'Buckle'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Heel Height': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': ['Flat', 'Low', 'Medium', 'High'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Health Care ': {
//     'Expiry Duration': {
//       'hintText': 'eg, 1 month, 6 month',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 2,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Usage Instructions': {
//       'hintText': 'eg. Apply twice daily',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Precautions': {
//       'hintText': 'e.g Avoid contact with eyes',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '0': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '1': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '2': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Home Decor & Furnishing': {
//     'Color': {
//       'hintText': 'e.g Beige, Gray',
//       'noOfAsnwers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': ['Wood', 'Metal', 'Glass', 'Fabric', 'Leather', 'Other'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Assembly Required': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': ['Yes', 'No'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': true,
//     },
//     'Size (in cm)': {
//       'hintText': 'e.g 80cm X 100cm X 20cm',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Pattern': {
//       'hintText': 'e.g Floral, Geometric',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Care Instructions': {
//       'hintText': 'eg.  Wipe with a damp cloth',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Home Essentials': {
//     'Color': {
//       'hintText': 'eg. Beige, Grey',
//       'noOfAsnwers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Material': {
//       'hintText': 'eg. Cotton, Wood',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'Custom'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Usage': {
//       'hintText': 'eg. Daily Use, Occasional Use',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Features': {
//       'hintText': 'eg. Waterproof, Foldable',
//       'noOfAsnwers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Maintenance': {
//       'hintText': 'eg. Easy to Clean, Requires Special Care',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
//   'Jewelry': {
//     'Material': {
//       'hintText': 'eg. Gold, Silver',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Color': {
//       'hintText': 'eg. Gold, Silver, Rose Gold',
//       'noOfAsnwers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Size': {
//       'hintText': '',
//       'noOfAsnwers': 2,
//       'dropDownItems': ['Small', 'Medium', 'Large', 'Adjustable'],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Occasion': {
//       'hintText': 'e.g., Wedding, Casual, Party',
//       'noOfAsnwers': 3,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     'Care Instructions': {
//       'hintText': 'e.g., Clean with a soft cloth, Avoid contact with chemicals',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//     '0': {
//       'hintText': '',
//       'noOfAsnwers': 1,
//       'dropDownItems': [],
//       'inputType': 0,
//       'maxLines': 1,
//       'compulsory': false,
//     },
//   },
// };
