import 'package:flutter/material.dart';

final Map<String, List<List<dynamic>>> householdCategoryProperties = {
  // Name, Hint Text, No of Answers, DropDown Items, TextInputType, Max Lines, Mandatory Info
  'Garments': [
    [
      'Category',
      '',
      2,
      ['Men\'s', 'Women\'s', 'Kids', 'Unisex'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Quantity',
      'eg. 1 set',
      1,
      [''],
      TextInputType.number,
      1,
      true,
    ],
    [
      'Size',
      '',
      1,
      ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Color',
      'eg. Red, Blue',
      3,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Material',
      '',
      1,
      ['Cotton', 'Polyester', 'Silk', 'Wool', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Weaving': [
    [
      'Material Type',
      '',
      2,
      ['Cotton', 'Wool', 'Silk', 'Synthetic', 'Other'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Quantity',
      'eg. 1 set',
      1,
      [''],
      TextInputType.number,
      1,
      true,
    ],
    [
      'Weave Type',
      '',
      2,
      ['Plain', 'Twill', 'Satin', 'Jacquard', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Color',
      'eg. Blue, Green',
      3,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Pattern',
      '',
      1,
      ['Striped', 'Checkered', 'Floral', 'Geometric', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Width (inches)',
      'eg. 5in',
      1,
      [''],
      TextInputType.number,
      1,
      false,
    ],
  ],
  'Tailoring': [
    [
      'Garment Type',
      '',
      2,
      ['Shirt', 'Pants', 'Dress', 'Suit', 'Skirt', 'Other'],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Quantity',
      'eg. 1 set',
      1,
      [''],
      TextInputType.number,
      1,
      true,
    ],
    [
      'Fabric Type',
      '',
      2,
      ['Cotton', 'Wool', 'Silk', 'Polyester', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Color',
      'eg. Red, Blue, Green...',
      3,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Size',
      'eg. XS, S, M, L...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Measurement Details',
      'eg. 15in X 10in',
      1,
      [''],
      TextInputType.text,
      3,
      false,
    ],
  ],
  'Food': [
    [
      'Cuisine Type',
      'Type of cuisine (eg. Italian, Chinese, etc.)',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Ingredients',
      'List of ingredients',
      3,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Allergens',
      'eg. Dairy, Nuts, Gluten...',
      1,
      [''],
      TextInputType.text,
      5,
      false,
    ],
    [
      'Spicy Level',
      'Level of spiciness (Mild, Medium, Hot)',
      2,
      ['Mild', 'Medium', 'Hot'],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      3,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      3,
      false,
    ],
  ],
  'Bakery Items': [
    [
      'Ingredients',
      'List of ingredients',
      3,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Allergens',
      'eg. Dairy, Nuts, Gluten...',
      1,
      [''],
      TextInputType.text,
      5,
      false,
    ],
    [
      'Flavor',
      '',
      2,
      ['Vanilla', 'Chocolate', 'Strawberry', 'Lemon', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Woodwork': [
    [
      'Product Type',
      'eg. Furniture, Decor, Tools...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Material',
      'eg. Oak, Pine, Teak...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Finish',
      'eg. Glossy, Matte, Stained...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Metalwork': [
    [
      'Product Type',
      'eg. Sculpture, Jewelry, Tools...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Material',
      'eg. Steel, Brass, Copper...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Finish',
      'eg. Polished, Brushed, Patina...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Beauty Products (Cosmetics)': [
    [
      'Product Category',
      'eg. Skincare, Makeup, Haircare...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Ingredients',
      'List of ingredients',
      3,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Type',
      'eg. Cleanser, Lipstick, Shampoo...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Skin Type',
      'eg. Normal, Oily, Dry, Combination...',
      2,
      ['Normal', 'Oily', 'Dry', 'Combination', 'Sensitive'],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Candles': [
    [
      'Scent',
      'eg. Vanilla, Lavender, Citrus...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Material',
      'eg. Soy Wax, Paraffin Wax, Beeswax...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Burn Time (in Hrs)',
      'eg. 6',
      1,
      [''],
      TextInputType.number,
      1,
      false,
    ],
    [
      'Color',
      'eg. Red, Blue, White...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Ayurvedic Products': [
    [
      'Product Type',
      'eg. Oil, Cream, Tablet...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Ingredients',
      'List of ingredients',
      3,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Benefits',
      'Benefits of the product',
      1,
      [''],
      TextInputType.text,
      5,
      false,
    ],
    [
      'Usage',
      'Usage instructions',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Packaging',
      'eg. Bottle, Jar, Box...',
      2,
      ['Bottle', 'Jar', 'Box', 'Tube', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.number,
      1,
      false,
    ],
  ],
  'Indian Snacks': [
    [
      'Snack Type',
      'eg. Namkeen, Sweets, Chaat...',
      1,
      [''],
      TextInputType.text,
      3,
      true,
    ],
    [
      'Ingredients',
      'List of ingredients',
      3,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Spiciness Level',
      'eg. Mild, Medium, Spicy...',
      2,
      ['Mild', 'Medium', 'Spicy'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Region',
      'eg. North, South, West, East...',
      2,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Papercraft': [
    [
      'Craft Type',
      'eg. Origami, Scrapbooking, Cardmaking...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Material',
      'eg. Paper, Cardstock, Origami Paper...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Tools',
      'List of tools used',
      3,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Difficulty Level',
      '',
      2,
      ['Beginner', 'Intermediate', 'Advanced'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Purpose',
      'eg. Decoration, Gift, Learning...',
      2,
      ['Decoration', 'Gift', 'Learning', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Jewelry': [
    [
      'Type',
      'eg. Necklace, Earrings, Bracelet...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Material',
      'eg. Gold, Silver, Platinum...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Gemstone (if used)',
      'eg. Sapphire, Ruby...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Style',
      'eg. Traditional, Modern, Vintage...',
      2,
      ['Traditional', 'Modern', 'Vintage', 'Bohemian', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Size',
      'eg. Small, Medium, Large...',
      2,
      ['Small', 'Medium', 'Large'],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.number,
      1,
      false,
    ],
  ],
  'Paintings': [
    [
      'Art Style',
      'eg. Abstract, Realism, Impressionism...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Medium',
      'eg. Oil, Acrylic, Watercolor...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Subject',
      'Subject of the painting',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Size',
      'eg. 10cm, 5in...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Frame',
      'eg. Wood, Metal, None...',
      2,
      ['Wood', 'Metal', 'None', 'Other'],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Sculptures': [
    [
      'Type',
      'eg. Figurative, Abstract, Bust...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Material',
      'eg. Marble, Bronze, Wood...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Dimensions',
      'Height x Width x Depth',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Weight',
      'eg. 10kg',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Style',
      'eg. Contemporary, Classical, Minimalist...',
      1,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Decorations': [
    [
      'Type',
      'eg. Vase, Figurine, Wall Art...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Material',
      'eg. Ceramic, Glass, Metal...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Theme',
      'eg. Modern, Vintage, Rustic...',
      1,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Size',
      '',
      2,
      ['Small', 'Medium', 'Large'],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Color',
      'eg. Red, Blue...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
  'Festive Essentials': [
    [
      'Item Type',
      'eg. Decorations, Lighting, Gifts...',
      1,
      [''],
      TextInputType.text,
      1,
      true,
    ],
    [
      'Material',
      'eg. Plastic, Glass, Metal...',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Theme',
      'eg. Christmas, Diwali, Halloween...',
      1,
      [],
      TextInputType.text,
      1,
      false,
    ],
    [
      'Usage',
      'Usage instructions or details',
      1,
      [''],
      TextInputType.text,
      5,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
    [
      '',
      '',
      1,
      [''],
      TextInputType.text,
      1,
      false,
    ],
  ],
};
