Map<String, Map<String, String>> householdSpecialCategories = {
  'Garments': {
    'Men\'s Shirts': '',
    'Women\'s Shirts': '',
    'Men\'s Trousers': '',
    'Women\'s Trousers': '',
    'Dresses': '',
    'Skirts': '',
    'Jackets': '',
    'Jeans': '',
    'Suits': '',
    'Activewear': '',
    'Baby Clothing': '',
    'Children\'s Clothing': '',
    'Hats': '',
    'Scarves': '',
    'Belts': '',
    'Gloves': '',
    'Ties': '',
    'Socks': '',
    'Men\'s Footwear': '',
    'Women\'s Footwear': '',
    'Children\'s Footwear': '',
    'Formal Wear': '',
    'Party Dresses': '',
    'Wedding Attire': '',
    'Coats': '',
    'Rainwear': '',
    'Blazers': '',
  },
  'Weaving': {
    'Cotton Fabric': '',
    'Wool Fabric': '',
    'Silk Fabric': '',
    'Linen Fabric': '',
    'Polyester Fabric': '',
    'Blended Fabric': '',
    'Handwoven Fabric': '',
    'Knitted Fabric': '',
    'Yarn': '',
    'Threads': '',
    'Looms': '',
    'Weaving Tools': '',
    'Dyes and Pigments': '',
    'Patterns': '',
    'Designs': '',
    'Textiles': '',
  },
  'Tailoring': {
    'Men\'s Suits': '',
    'Women\'s Suits': '',
    'Men\'s Shirts': '',
    'Women\'s Shirts': '',
    'Trousers': '',
    'Dresses': '',
    'Skirts': '',
    'Jackets': '',
    'Coats': '',
    'Blazers': '',
    'Alterations': '',
    'Custom Designs': '',
    'Uniforms': '',
    'Wedding Attire': '',
    'Formal Wear': '',
    'Casual Wear': '',
    'Fabric': '',
    'Buttons': '',
    'Zippers': '',
    'Thread': '',
    'Patterns': '',
    'Sewing Tools': '',
  },
  'Food': {
    'Fruits': '',
    'Vegetables': '',
    'Dairy Products': '',
    'Grains': '',
    'Baked Goods': '',
    'Canned Foods': '',
    'Frozen Foods': '',
    'Snacks': '',
    'Beverages': '',
    'Condiments': '',
    'Spices': '',
    'Herbs': '',
    'Oils': '',
    'Pasta': '',
    'Rice': '',
    'Nuts': '',
    'Seeds': '',
    'Sweets': '',
  },
  'Bakery Items': {
    'Bread': '',
    'Rolls': '',
    'Bagels': '',
    'Muffins': '',
    'Croissants': '',
    'Cookies': '',
    'Cakes': '',
    'Pies': '',
    'Pastries': '',
    'Donuts': '',
    'Tarts': '',
    'Brownies': '',
    'Scones': '',
    'Cupcakes': '',
    'Buns': '',
    'Danishes': '',
    'Eclairs': '',
    'Macarons': '',
    'Biscotti': '',
    'Crackers': '',
  },
  'Woodwork': {
    'Furniture': '',
    'Cabinets': '',
    'Shelves': '',
    'Tables': '',
    'Chairs': '',
    'Doors': '',
    'Windows': '',
    'Picture Frames': '',
    'Carvings': '',
    'Wooden Toys': '',
    'Cutting Boards': '',
    'Wooden Utensils': '',
    'Wooden Boxes': '',
    'Wooden Sculptures': '',
    'Wooden Decor': '',
    'Wooden Panels': '',
    'Wooden Flooring': '',
    'Wooden Signs': '',
    'Wooden Instruments': '',
    'Wooden Jewelry': '',
  },
  'Metalwork': {
    'Metal Art': '',
    'Metal Sculptures': '',
    'Metal Furniture': '',
    'Metal Decor': '',
    'Metal Jewelry': '',
    'Metal Utensils': '',
    'Metal Tools': '',
    'Metalworking Supplies': '',
    'Metal Sheets': '',
    'Metal Pipes': '',
    'Metal Fasteners': '',
    'Metal Hardware': '',
    'Metal Fixtures': '',
    'Metal Components': '',
    'Metal Casting': '',
    'Metal Forging': '',
    'Metal Engraving': '',
    'Metal Finishing': '',
    'Metal Plating': '',
    'Metal Alloys': '',
  },
  'Beauty Products (Cosmetics)': {
    'Lipsticks': '',
    'Foundation': '',
    'Mascara': '',
    'Eyeshadow': '',
    'Eyeliner': '',
    'Blush': '',
    'Highlighter': '',
    'Bronzer': '',
    'Makeup Remover': '',
    'Skincare Products': '',
    'Moisturizers': '',
    'Serums': '',
    'Facial Cleansers': '',
    'Toners': '',
    'Face Masks': '',
    'Eye Creams': '',
    'Lip Balms': '',
    'Hair Care Products': '',
    'Shampoo': '',
    'Conditioner': '',
    'Hair Styling Products': '',
    'Hair Color': '',
    'Perfumes': '',
    'Nail Polish': '',
    'Nail Care Products': '',
    'Makeup Brushes': '',
  },
  'Candles': {
    'Scented Candles': '',
    'Pillar Candles': '',
    'Jar Candles': '',
    'Tealight Candles': '',
    'Floating Candles': '',
    'Votive Candles': '',
    'Taper Candles': '',
    'Beeswax Candles': '',
    'Handmade Candles': '',
    'Decorative Candles': '',
    'Seasonal Candles': '',
    'Aromatherapy Candles': '',
    'Emergency Candles': '',
    'Candle Holders': '',
    'Candle Accessories': '',
    'Candle Making Supplies': '',
    'Wax Melts': '',
    'Incense Sticks': '',
    'Room Sprays': '',
  },
  'Ayurvedic Products': {
    'Ayurvedic Medicine': '',
    'Herbal Supplements': '',
    'Ayurvedic Skincare': '',
    'Ayurvedic Hair Care': '',
    'Ayurvedic Massage Oils': '',
    'Ayurvedic Teas': '',
    'Ayurvedic Personal Care': '',
    'Ayurvedic Digestive Aids': '',
    'Ayurvedic Immune Boosters': '',
    'Ayurvedic Joint Care': '',
    'Ayurvedic Weight Management': '',
    'Ayurvedic Dental Care': '',
    'Ayurvedic Cosmetics': '',
    'Ayurvedic Bath Products': '',
    'Ayurvedic Essential Oils': '',
    'Ayurvedic Health Tonics': '',
    'Ayurvedic Herbal Extracts': '',
    'Ayurvedic Stress Relief': '',
    'Ayurvedic Anti-Aging Products': '',
    'Ayurvedic Beauty Supplements': '',
  },
  'Indian Snacks': {
    'Samosa': '',
    'Pakora': '',
    'Chaat': '',
    'Bhel Puri': '',
    'Dhokla': '',
    'Vada': '',
    'Namkeen': '',
    'Sweets': '',
    'Biscuits': '',
    'Chips': '',
    'Nuts': '',
    'Candies': '',
    'Popcorn': '',
    'Pickles': '',
    'Chutneys': '',
    'Snack Mixes': '',
    'Frozen Snacks': '',
    'Instant Mixes': '',
    'Healthy Snacks': '',
  },
  'Papercraft': {
    'Greeting Cards': '',
    'Origami': '',
    'Scrapbooking Supplies': '',
    'Paper Quilling': '',
    'Paper Models': '',
    'Decoupage': '',
    'Card Making Supplies': '',
    'Paper Cutting': '',
    'Embossing Tools': '',
    'Paper Sculpture': '',
    'Paper Flowers': '',
    'Bookbinding Kits': '',
    'Paper Mache': '',
    'Papercraft Tools': '',
    'Stationery': '',
    'Paper Beads': '',
    'Paper Art Kits': '',
    'Paper Stickers': '',
    'Paper Craft Books': '',
    'DIY Paper Projects': '',
  },
  'Jewelry': {
    'Rings': '',
    'Necklaces': '',
    'Earrings': '',
    'Bracelets': '',
    'Anklets': '',
    'Brooches': '',
    'Pendants': '',
    'Chains': '',
    'Bangles': '',
    'Charms': '',
    'Jewelry Sets': '',
    'Men\'s Jewelry': '',
    'Women\'s Jewelry': '',
    'Children\'s Jewelry': '',
    'Fine Jewelry': '',
    'Fashion Jewelry': '',
    'Handmade Jewelry': '',
    'Wedding Jewelry': '',
    'Ethnic Jewelry': '',
    'Body Jewelry': '',
    'Custom Jewelry': '',
  },
  'Paintings': {
    'Oil Paintings': '',
    'Watercolor Paintings': '',
    'Acrylic Paintings': '',
    'Mixed Media Paintings': '',
    'Abstract Paintings': '',
    'Landscape Paintings': '',
    'Portrait Paintings': '',
    'Still Life Paintings': '',
    'Modern Art Paintings': '',
    'Contemporary Paintings': '',
    'Realistic Paintings': '',
    'Impressionist Paintings': '',
    'Expressionist Paintings': '',
    'Pop Art Paintings': '',
    'Miniature Paintings': '',
    'Traditional Paintings': '',
    'Folk Art Paintings': '',
    'Nature Paintings': '',
    'Cityscape Paintings': '',
    'Seascape Paintings': '',
  },
  'Sculptures': {
    'Bronze Sculptures': '',
    'Wood Sculptures': '',
    'Stone Sculptures': '',
    'Metal Sculptures': '',
    'Clay Sculptures': '',
    'Glass Sculptures': '',
    'Abstract Sculptures': '',
    'Figurative Sculptures': '',
    'Modern Sculptures': '',
    'Contemporary Sculptures': '',
    'Traditional Sculptures': '',
    'Outdoor Sculptures': '',
    'Indoor Sculptures': '',
    'Sculptural Installations': '',
    'Sculpture Replicas': '',
    'Custom Sculptures': '',
    'Animal Sculptures': '',
    'Human Sculptures': '',
    'Sculpture Tools': '',
    'Sculpture Books': '',
  },
  'Decorations': {
    'Wall Decor': '',
    'Artificial Plants': '',
    'Vases': '',
    'Candles and Holders': '',
    'Mirrors': '',
    'Clocks': '',
    'Photo Frames': '',
    'Decorative Bowls': '',
    'Sculptures': '',
    'Decorative Figures': '',
    'Wind Chimes': '',
    'Decorative Boxes': '',
    'Rugs and Carpets': '',
    'Throws and Blankets': '',
    'Cushions and Pillows': '',
    'Table Decor': '',
    'Room Dividers': '',
    'Holiday Decorations': '',
    'Party Supplies': '',
    'Outdoor Decor': '',
  },
  'Festive Essentials': {
    'Decorative Lights': '',
    'String Lights': '',
    'Lanterns': '',
    'Candles and Holders': '',
    'Garlands': '',
    'Ornaments': '',
    'Christmas Trees': '',
    'Wreaths': '',
    'Tableware': '',
    'Party Decorations': '',
    'Gift Wrapping Supplies': '',
    'Holiday Cards': '',
    'Festive Clothing': '',
    'Seasonal Foods': '',
    'Fireworks': '',
    'Home Fragrances': '',
    'Holiday Music': '',
    'DIY Craft Kits': '',
    'Cultural Decorations': '',
    'Customized Gifts': '',
  },
};
