Map<String, Map<String, String>> specialCategories = {
  'Grocery': {
    'Fruits':
        'https://www.google.com/imgres?q=png%20images%20grocery%20images%20free%20download&imgurl=https%3A%2F%2Fw7.pngwing.com%2Fpngs%2F669%2F488%2Fpng-transparent-shopping-cart-fruit-vegetable-supermarket-shopping-cart-natural-foods-food-supermarket-thumbnail.png&imgrefurl=https%3A%2F%2Fwww.pngwing.com%2Fen%2Fsearch%3Fq%3Dsupermarket&docid=1Az4al4kbsUdhM&tbnid=pTdK0CH9YXaubM&vet=12ahUKEwjSvv33wreFAxUvQ2cHHeh8BVIQM3oECHsQAA..i&w=360&h=383&hcb=2&ved=2ahUKEwjSvv33wreFAxUvQ2cHHeh8BVIQM3oECHsQAA',
    'Vegetables': '',
    'Baked':
        'https://www.google.com/imgres?q=png%203d%20images%20baked%20itoms%20images%20free%20download&imgurl=https%3A%2F%2Fpng.pngtree.com%2Fpng-vector%2F20190123%2Fourmid%2Fpngtree-cartoon-birthday-cake-cake-cupcake-hand-painted-birthday-cake-png-image_542262.jpg&imgrefurl=https%3A%2F%2Fpngtree.com%2Fso%2Fbaked-goods&docid=50McUMI04qHahM&tbnid=aPDBabO5A34YXM&vet=12ahUKEwjBwojExbeFAxUuXmwGHYBxD4oQM3oECFMQAA..i&w=360&h=360&hcb=2&ved=2ahUKEwjBwojExbeFAxUuXmwGHYBxD4oQM3oECFMQAA',
    'Canned':
        'https://www.google.com/imgres?q=png%203d%20images%20canned%20itoms%20images%20free%20download&imgurl=https%3A%2F%2Fimg.lovepik.com%2Fpng%2F20231129%2Fplastic-protien-jar-3d-rendering-png-cans-tin_724047_wh860.png&imgrefurl=https%3A%2F%2Flovepik.com%2Fimage-380724047%2Fplastic-protien-jar-3d-rendering-png-cans-tin.html&docid=PpEerd63IpLdGM&tbnid=7tKgXhM7cz0viM&vet=12ahUKEwj8896nxreFAxVTRmwGHe-nDG4QM3oECE0QAA..i&w=860&h=860&hcb=2&itg=1&ved=2ahUKEwj8896nxreFAxVTRmwGHe-nDG4QM3oECE0QAA',
    'Beverages':
        'https://www.google.com/imgres?q=transparant%20background%20png%203d%20images%20beverages%20itoms%20images%20free%20download&imgurl=https%3A%2F%2Fimg.freepik.com%2Ffree-photo%2Fbottles-with-colorful-cocktail-ice_144627-21737.jpg%3Fsize%3D626%26ext%3Djpg%26ga%3DGA1.1.735520172.1712275200%26semt%3Dais&imgrefurl=https%3A%2F%2Fwww.freepik.com%2Ffree-photos-vectors%2Fsoft-drinks-png&docid=R28pCmuJJt0iMM&tbnid=iGNquH7azH9RfM&vet=12ahUKEwisloPKyLeFAxWlcGwGHZXEDsAQM3oECEMQAA..i&w=626&h=540&hcb=2&ved=2ahUKEwisloPKyLeFAxWlcGwGHZXEDsAQM3oECEMQAA',
    'Candies':
        'https://www.google.com/imgres?q=transparant%20background%20png%203d%20images%20candies%20itoms%20images%20free%20download&imgurl=https%3A%2F%2Fimages.creativefabrica.com%2Fproducts%2Fpreviews%2F2023%2F10%2F27%2FvWfI3vbJZ%2F2XMsm9taovAIafngUJ5iYAvqMrD-mobile.jpg&imgrefurl=https%3A%2F%2Fwww.creativefabrica.com%2Fprod%2Fcolorful-candy-jar-with-assorted-sweet-treats-png-vWfI3vbJZ%2F&docid=zmehihZBpRfduM&tbnid=3VetugCBUnsjFM&vet=12ahUKEwjBnZbtybeFAxUjd2wGHZwvCvQQM3oECCkQAA..i&w=552&h=552&hcb=2&ved=2ahUKEwjBnZbtybeFAxUjd2wGHZwvCvQQM3oECCkQAA',
    'Snacks':
        'https://www.google.com/imgres?q=transparant%20background%203d%20images%20snacks%20itoms%20images%20free%20download&imgurl=https%3A%2F%2Fstatic.vecteezy.com%2Fsystem%2Fresources%2Fthumbnails%2F025%2F065%2F315%2Fsmall_2x%2Ffast-food-meal-with-ai-generated-free-png.png&imgrefurl=https%3A%2F%2Fwww.vecteezy.com%2Ffree-png%2Ffood&docid=42UKLvLEmiaAqM&tbnid=YqHUgmTJORfq_M&vet=12ahUKEwivsKyhzLeFAxWzV2wGHcPQBEw4ChAzegQIIBAA..i&w=788&h=400&hcb=2&ved=2ahUKEwivsKyhzLeFAxWzV2wGHcPQBEw4ChAzegQIIBAA',
    'Frozen':
        'https://www.google.com/imgres?q=3d%20model%20transparent%20background%203d%20images%20frozen%20food%20items%20images%20free%20download&imgurl=https%3A%2F%2Fmedia.sketchfab.com%2Fmodels%2F914ab4c2d96849c2b3e30c5a6495bb7c%2Fthumbnails%2F99b57ef7dd1e486e8c7449dd05bebb2c%2F41d712f612dc456db6453304478e1703.jpeg&imgrefurl=https%3A%2F%2Fsketchfab.com%2F3d-models%2Ffrozen-food-aisle-right-side-914ab4c2d96849c2b3e30c5a6495bb7c&docid=NzDnFJK5dU020M&tbnid=AEEo11zR-kOPBM&vet=12ahUKEwiL2c_2z7eFAxU_R2wGHVZDDEEQM3oECGcQAA..i&w=1920&h=1080&hcb=2&ved=2ahUKEwiL2c_2z7eFAxU_R2wGHVZDDEEQM3oECGcQAA',
    'Rice & Cereal':
        'https://www.google.com/imgres?q=whole%20grains%20transparent%20background%203d%20images%20rice%20and%20cereal%20packets%20items%20images%20free%20download&imgurl=https%3A%2F%2Fw7.pngwing.com%2Fpngs%2F212%2F294%2Fpng-transparent-whole-grain-whole-food-cereal-whole-wheat-bread-brown-rice-rice-natural-foods-food-eating.png&imgrefurl=https%3A%2F%2Fwww.pngwing.com%2Fen%2Ffree-png-zwrrl&docid=7gKgCTOn-vKGXM&tbnid=2_gLeAVM28kPBM&vet=12ahUKEwiv24CS0beFAxWcR2wGHQ5hCtUQM3oECGQQAA..i&w=920&h=602&hcb=2&ved=2ahUKEwiv24CS0beFAxWcR2wGHQ5hCtUQM3oECGQQAA',
  },
  'Pharmacies': {
    'Clincial Medicines': '',
    'Dermatology': '',
    'Oncology': '',
    'Emergency Medicines': '',
    'Pain Killers': '',
    'Hematology': '',
    'Cardiology': '',
    'Endocrinology': '',
    'Hepatology': '',
    'Immunology': '',
    'Nephrology': '',
    'Internal Medicines': '',
    'Medical Equipments': '',
  },
  'Electronics': {
    'Mobile & Tabs': '',
    'Televisions': '',
    'Headphones': '',
    'Cameras': '',
    'Gaming': '',
    'Air Conditioners': '',
    'Refrigerators': '',
    'Washing Machines': '',
    'Speakers': '',
    'Screen Protectors': '',
    'Power Banks': '',
    'Software': '',
    'Laptops': '',
    'Drives & Storage': '',
    'Printers & Ink': '',
    'Desktop': '',
    'Home Appliances': '',
  },
  'Clothing and Apparel': {
    'T Shirt': '',
    'Polos': '',
    'Shirts': '',
    'Jeans': '',
    'Innerwear': '',
    'Sunglasses': '',
    'Watches': '',
    'Shoes': '',
    'Sportswear': '',
    'Wallets': '',
    'Western': '',
    'Ethnic': '',
    'Sandals': '',
  },
  'Restaurant & Cafes': {
    'Appetizers': '',
    'Soups': '',
    'Salads': '',
    'Sides': '',
    'Desserts': '',
    'Beverages': '',
    'Dips': '',
    'Western': '',
    'Chinese': '',
    'Indian': '',
  },
  'Beauty and Cosmetics': {
    'Skin Care': '',
    'Hair Care': '',
    'Nail Care': '',
    'Oral Hygiene': '',
    'Lipsticks': '',
    'Eye Shadow & Eye Liners': '',
    'Tattoos': '',
  },
  'Furniture': {
    'Chairs': '',
    'Benches': '',
    'Beds': '',
    'Couches': '',
    'Toddlers': '',
    'Tables': '',
    'Desks': '',
    'Shelfs': '',
    'Cupboards': '',
    'Racks': '',
  },
  'Jewelry': {
    'Body Piercings': '',
    'Bracelets': '',
    'Brooches': '',
    'Necklaces': '',
    'Rings': '',
    'Luxury Watches': '',
    'Gem Stones': '',
    'Pendants': '',
  },
  'Decorations': {
    'Clocks': '',
    'Mirrors': '',
    'Frames': '',
    'Vases': '',
    'Rugs': '',
    'Cushions': '',
    'Paintings': '',
    'Wall Stickers': '',
    'Screens': '',
    'Room Dividers': '',
    'Curtains': '',
    'Plant Pots': '',
    'Flower Pot Holder': '',
    'Vertical Garden': '',
  },
  'Bookstores and Stationery': {
    'Fiction Book': '',
    'Non Fiction Books': '',
    'Educational Books': '',
    'Necessary': '',
    'Activity Book': '',
    'Coloring': '',
    'Presentation Goods': '',
  },
  'Building Materials and Hardware': {
    'Steel': '',
    'Cement': '',
    'Concrete': '',
    'Wires': '',
    'Wood': '',
    'Stone': '',
    'Bricks': '',
  },
  'Automobile Parts and Accessories': {
    'Brakes': '',
    'Battery': '',
    'Axles': '',
    'Transmittors': '',
    'Clutch': '',
    'Lights': '',
    'Engines': '',
    'Suspension': '',
    'Seat Covers': '',
    'Helmets & Gloves': '',
  },
  'Gifts and Novelty': {
    'Mugs': '',
    'Frames': '',
    'Chocolates': '',
    'Accessories': '',
    'Gift Hampers': '',
    'Handcrafted': '',
    'Pet Gifts': '',
    'Religious': '',
  },
  'Toys': {
    'STEM Toys': '',
    'Stuffed Toys': '',
    'Mechanical Toys': '',
    'Puzzles': '',
    'Educational Toys': '',
    'Vehicles': '',
    'Dolls': '',
    'Musical Toys': '',
    'Baby Toys': '',
    'Ridables': '',
    'Radio Controlled': '',
    'Animal Toys': '',
    'Cards': '',
    'Action': '',
    'Construction Toys': '',
    'Creative Toys': '',
    'Blocks & Bricks': '',
    'Home Sets': '',
    'Spinners': '',
    'Robots': '',
  },
  'Sports Goods': {
    'Cricket': '',
    'Badminton': '',
    'Roller Skates': '',
    'Hockey': '',
    'Bowling': '',
    'Baseball': '',
    'Rugby': '',
    'Darts & Targets': '',
    'Football': '',
    'Sportswear': '',
    'Balls': '',
  },
  'Agriculture and Farm Supply': {
    'Irrigation Machines': '',
    'Seeds': '',
    'Fertilizers': '',
    'Farming Tools': '',
    'Soil': '',
    'Ploughs': '',
    'Planters': '',
    'Containers': '',
    'Harvester': '',
    'Big Machines': '',
  },
};
