Map<String, Map<String, List<String>>> servicesMap = {
  'Home': {
    'Kitchen': [
      'Appliance Repair',
      'Plumbing',
      'Electrical',
      'Cabinetry Repair/Installation',
      'Countertop Installation/Repair',
      'Flooring Installation/Repair',
      'Kitchen Remodeling',
    ],
    'Bedroom': [
      'Furniture Assembly/Repair',
      'Closet Organization',
      'Painting/Wallpapering',
      'Bed Frame Assembly/Repair',
      'Mattress Cleaning/Replacement',
    ],
    'Bathroom': [
      'Plumbing',
      'Tile Repair/Installation',
      'Fixture Replacement/Repair',
      'Bathroom Remodeling',
      'Grout Cleaning/Replacement',
      'Shower Door Installation/Repair',
    ],
    'Cleaning': [
      'General Cleaning',
      'Deep Cleaning',
      'Carpet Cleaning',
      'Window Cleaning',
      'Upholstery Cleaning',
      'Air Duct Cleaning',
    ],
    'Outdoor Home': [
      'Lawn Care',
      'Gardening/Landscaping',
      'Deck/Patio Maintenance',
      'Exterior Painting/Repairs',
      'Roof Repair/Replacement',
      'Fence Installation/Repair',
    ],
    'Miscellaneouss': [
      'Home Security Installation',
      'HVAC Repair/Installation',
      'Pest Control',
      'Home Theater Installation',
      'Home Organization Services',
    ],
  },
  'Office': {
    'Office Services': [
      'Office Cleaning',
      'Office Equipment Maintenance',
      'IT Support',
      'Office Furniture Assembly/Installation',
      'Commercial Painting/Repairs',
      'Office Moving Services',
    ],
    'Event Services': [
      'Event Planning/Coordination',
      'Catering',
      'Photography/Videography',
      'Party Rental Equipment',
      'Entertainment Booking',
      'Event Cleanup Services',
    ],
    // 'Public Space Services': [
    //   'Park Maintenance',
    //   'Public Restroom Cleaning',
    //   'Street Cleaning',
    //   'Graffiti Removal',
    //   'Public Playground Maintenance',
    //   'Public Garden Maintenance',
    // ],
  },
  'Outdoor': {
    'Vehicle Services': [
      'Mechanical Repairs',
      'Detailing',
      'Tire Services',
      'Battery Replacement',
      'Oil Changes',
      'Brake Services',
    ],
    'Roadside Assistance': [
      'Towing',
      'Jump Starts',
      'Lockout Assistance',
      'Fuel Delivery',
      'Tire Changes',
    ],
    'Delivery Services': [
      'Food Delivery',
      'Package Delivery',
      'Grocery Delivery',
      'Courier Services',
      'Alcohol Delivery',
    ],
    'Mobile Repair Services': [
      'Mobile Phone Repair',
      'Laptop/Tablet Repair',
      'Bicycle Repair',
      'Scooter/Motorcycle Repair',
      'Smartwatch Repair',
      'Gaming Console Repair',
    ],
  },
};
