Map<String, String> placeImageMap = {
  'Home': '',
  'Office': '',
  'Outdoor': '',
  'Retail Stores': '',
  'Educational Institutes': '',
};

Map<String, String> categoryImageMap = {
  'Kitchen Services': '',
  'Bedroom Services': '',
  'Bathroom Services': '',
  'Living Room Services': '',
  'Outdoor Services': '',
  'Workspace Services': '',
  'Meeting Rooms Services': '',
  'Reception Area Services': '',
  'Common Areas Services': '',
  'Workplace Wellness Services': '',
  'Lawn and Garden Services': '',
  'Exterior Home Services': '',
  'Pool and Spa Services': '',
  'Pest Control Services': '',
  'Outdoor Event Services': '',
  'Grocery Stores': '',
  'Clothing Stores': '',
  'Electronics Stores': '',
  'Home Improvement Stores': '',
  'Department Stores': '',
  'Schools': '',
  'Colleges and Universities': '',
  'Vocational Institutes': '',
  'Language Schools': '',
  'Online Learning Platforms': '',
  'Temples': '',
  'Mosques': '',
  'Churches': '',
  'Gurdwaras': '',
  'Synagogues': '',
};

Map<String, String> subCategoryImageMap = {
  // Home Categories
  'Cooking Traditional Meals': '',
  'Dishwashing': '',
  'Kitchen Cleaning': '',
  'Grocery Shopping': '',
  'Meal Preparation': '',
  'Bed Making': '',
  'Laundry': '',
  'Closet Organization': '',
  'Dusting': '',
  'Toilet Cleaning': '',
  'Shower Cleaning': '',
  'Sink Cleaning': '',
  'Mirror Cleaning': '',
  'Toiletry Restocking': '',
  'Vacuuming': '',
  'Carpet Cleaning': '',
  'Furniture Polishing': '',
  'Electronics Maintenance': '',
  'Lawn Mowing': '',
  'Gardening': '',
  'Weeding': '',
  'Exterior Cleaning': '',
  'Terrace/Garden Maintenance': '',
  // Office Categories
  'Desk Organization': '',
  'Surface Cleaning': '',
  'Keyboard Cleaning': '',
  'Document Management': '',
  'Office Supplies Replenishment': '',
  'Meeting Preparation': '',
  'Audio-Visual Setup': '',
  'Whiteboard Cleaning': '',
  'Furniture Arrangement': '',
  'Front Desk Organization': '',
  'Waiting Area Maintenance': '',
  'Reading Material Management': '',
  'Refreshment Setup': '',
  'Lobby Cleaning': '',
  'Floor Sweeping': '',
  'Trash Disposal': '',
  'Signage Maintenance': '',
  'Ergonomic Setup': '',
  'Stress Relief Activities': '',
  'Fitness Classes': '',
  'Safety Training': '',
  // Outdoor Categories
  'Lawn Care': '',
  'Garden Maintenance': '',
  'Pruning': '',
  'Window Washing': '',
  'Roof and Gutter Maintenance': '',
  'Painting Touch-ups': '',
  'Exterior Fixture Maintenance': '',
  'Pool Cleaning': '',
  'Chemical Balancing': '',
  'Spa Maintenance': '',
  'Basic Repairs': '',
  'General Pest Control': '',
  'Mosquito Control': '',
  'Rodent Prevention': '',
  'Wildlife Deterrence': '',
  'Event Setup': '',
  'Decoration Arrangement': '',
  'Food and Beverage Setup': '',
  'Cleanup Assistance': '',
  // Retail Stores Categories
  'Shopping': '',
  'Fruit and Vegetable Selection': '',
  'Dairy Pickup': '',
  'Spice Selection': '',
  'Clothing Selection': '',
  'Accessories Shopping': '',
  'Fitting Room Try-Ons': '',
  'Footwear Selection': '',
  'Electronics Selection': '',
  'Device Setup': '',
  'Home Appliance Maintenance': '',
  'Basic Troubleshooting': '',
  'Tool Selection': '',
  'Paint and Wallpaper Shopping': '',
  'Basic Home Repairs': '',
  'Lighting Fixture Replacement': '',
  'General Shopping': '',
  'Toy Selection': '',
  'Home Goods Shopping': '',
  'Electronics Purchase': '',
  // Educational Institute Categories
  'Homework Completion': '',
  'Extracurricular Participation': '',
  'Library Usage': '',
  'Student Organization Involvement': '',
  'Class Attendance': '',
  'Homework Submission': '',
  'Library Research': '',
  'Study Group Participation': '',
  'Trade Skill Development': '',
  'Technical Training': '',
  'Certification Preparation': '',
  'Job Search Assistance': '',
  'Language Learning': '',
  'Language Practice': '',
  'Language Exam Preparation': '',
  'Language Immersion Programs': '',
  'Online Course Completion': '',
  'Self-Study': '',
  'Skill Development': '',
  // Religious Places Categories
  'Prayer Attendance': '',
  'Scripture Reading': '',
  'Community Events Participation': '',
  'Volunteering': '',
};
