Map<String, String> placeImageMap = {
  'Home': '',
  'Office': '',
  'Outdoor': '',
};

Map<String, String> categoryImageMap = {
  'Kitchen': '',
  'Bedroom': '',
  'Bathroom': '',
  'Cleaning': '',
  'Outdoor Home': '',
  'Miscellaneous': '',
  'Office Services': '',
  'Event Services': '',
  // 'Public Space Services': '',
  'Vehicle Services': '',
  'Roadside Assistance': '',
  'Delivery Services': '',
  'Mobile Repair Services': '',
};

Map<String, String> subCategoryImageMap = {
  'Appliance Repair': '',
  'Plumbing': '',
  'Electrical': '',
  'Cabinetry Repair/Installation': '',
  'Countertop Installation/Repair': '',
  'Flooring Installation/Repair': '',
  'Kitchen Remodeling': '',
  'Furniture Assembly/Repair': '',
  'Closet Organization': '',
  'Painting/Wallpapering': '',
  'Bed Frame Assembly/Repair': '',
  'Mattress Cleaning/Replacement': '',
  'Tile Repair/Installation': '',
  'Fixture Replacement/Repair': '',
  'Bathroom Remodeling': '',
  'Grout Cleaning/Replacement': '',
  'Shower Door Installation/Repair': '',
  'General Cleaning': '',
  'Deep Cleaning': '',
  'Carpet Cleaning': '',
  'Window Cleaning': '',
  'Upholstery Cleaning': '',
  'Air Duct Cleaning': '',
  'Lawn Care': '',
  'Gardening/Landscaping': '',
  'Deck/Patio Maintenance': '',
  'Exterior Painting/Repairs': '',
  'Roof Repair/Replacement': '',
  'Fence Installation/Repair': '',
  'Home Security Installation': '',
  'HVAC Repair/Installation': '',
  'Pest Control': '',
  'Home Theater Installation': '',
  'Home Organization Services': '',
  'Mechanical Repairs': '',
  'Detailing': '',
  'Tire Services': '',
  'Battery Replacement': '',
  'Oil Changes': '',
  'Brake Services': '',
  'Towing': '',
  'Jump Starts': '',
  'Lockout Assistance': '',
  'Fuel Delivery': '',
  'Tire Changes': '',
  'Food Delivery': '',
  'Package Delivery': '',
  'Grocery Delivery': '',
  'Courier Services': '',
  'Alcohol Delivery': '',
  'Mobile Phone Repair': '',
  'Laptop/Tablet Repair': '',
  'Bicycle Repair': '',
  'Scooter/Motorcycle Repair': '',
  'Smartwatch Repair': '',
  'Gaming Console Repair': '',
  'Office Cleaning': '',
  'Office Equipment Maintenance': '',
  'IT Support': '',
  'Office Furniture Assembly/Installation': '',
  'Commercial Painting/Repairs': '',
  'Office Moving Services': '',
  'Event Planning/Coordination': '',
  'Catering': '',
  'Photography/Videography': '',
  'Party Rental Equipment': '',
  'Entertainment Booking': '',
  'Event Cleanup Services': '',
  'Park Maintenance': '',
  'Public Restroom Cleaning': '',
  'Street Cleaning': '',
  'Graffiti Removal': '',
  'Public Playground Maintenance': '',
  'Public Garden Maintenance': '',
};
